### ISSUE TITLE
Which versions of riemann, if any, are susceptible to log4shell (log4j vulnerability)?

### ISSUE THREAD

**Issue by ahungry** [riemann/riemann#1001]
http://slf4j.org/log4shell.html

Which versions of riemann may be impacted?  For instance, riemann-0.3.1 uses slf4j-over-log4j, which the linked page notes could be exposed to the log4shell issue.

**Comment by jamtur01** [comment]
Riemann is not vulnerable Hi - we use Logback as the backend to slf4j - which isn't vulnerable to the issue.
