### ISSUE TITLE
Docker image builds switched architecture

### ISSUE THREAD

**Issue by xificurC** [riemann/riemann#1002]
**Describe the bug**
Since 0.3.7 docker image builds are ARM builds. Before they were x86

**Expected behavior**
x86 images should still be available

**Additional context**
I guess @jamtur01 you have an ARM machine and this kind of leaked through? :)

**Comment by jamtur01** [comment]
Argh. I am an idiot. I forgot to update buildx. :( 

I'll fix this momentarily.

**Comment by jamtur01** [comment]
This should be fixed. I am going to move build to GitHub shortly too.
