### ISSUE TITLE
Logback needs update to 1.2.10

### ISSUE THREAD

**Issue by sanel** [riemann/riemann#1006]
**Describe the bug**
Current version of logback used is 1.2.3 and according to [this](https://github.com/advisories/GHSA-668q-qrv7-99fm), there are some security issues with it. Also logback site [confirms](https://logback.qos.ch/news.html) it.

AFAIK, this CVE to work will need a write access to `logback.xml`, which is shipped in riemann jar or riemann needs to be started/loaded with a custom logback.xml

@jamtur01 I believe this is an easy commit, but I can create a PR if you want.

**Comment by jamtur01** [comment]
Thanks. I've upgraded the dependency in 905516e0bd76651b0dc3963413d4ec9963bea0cd
