### ISSUE TITLE
Has 0.3.8 been retagged?

### ISSUE THREAD

**Issue by SMillerDev** [riemann/riemann#1013]
When Homebrew [updated the 0.3.8 release in december last year](https://github.com/Homebrew/homebrew-core/commit/eb40e288f4581c837adc6670508ffe1946774371) it had the checksum `7490c8808c235ca6ba3d96459296dc922840a0a381f02496a4a370ef668a65ef` but when I download it now it has `3234d4aea762f4aef53e1a4bcd1de5a9d3a234cec896687c1d67f70543abf9bd`.
The [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do so we generally err on the side of caution and ask upstream what happened.

**Comment by jamtur01** [comment]
This is as a result of #1002. Given the circumstances, I didn't want the wrong architecture images floating around, so IMHO "the insane thing" was a better choice.
