### ISSUE TITLE
`influxdb2` keeps accumulating background threads

### ISSUE THREAD

**Issue by node13h** [riemann/riemann#1027]
**Describe the bug**
Posting to InfluxDB using `influxdb2` keeps accumulating background threads until Riemann or machine crashes.

**To Reproduce**
1.Configure Riemann to send data from few dozen reasonably active streams using `influxdb2`
2. Wait and observe accumulating threads using VisualVM.

**Expected behavior**
Stable operation.

**Screenshots**
![image](https://user-images.githubusercontent.com/3377821/189540964-93b5e8a8-6dc5-4a8c-ac13-66f4744d576f.png)
![image](https://user-images.githubusercontent.com/3377821/189541321-ad5241db-f851-41fb-8367-2f9f75ace5d6.png)

**Background (please complete the following information):**
 - OS: CentOS 7
 - Java/JVM version 1.8.0_322-b06
 - Riemann version 0.3.8

**Additional context**
[WriteApi](https://influxdata.github.io/influxdb-client-java/influxdb-client-java/apidocs/index.html) creates a background thread and is supposed to run as a singleton. `riemann.influxdb2.post-data` creates a new instance of `WriteApi` on each invocation.
Using [WriteApiBlocking](https://influxdata.github.io/influxdb-client-java/influxdb-client-java/apidocs/index.html) fixes the issue.

**Comment by jarpy** [comment]
It's not super-obvious, but the docs for `influx2` suggest that:

> For performance, you should wrap this stream with batch or an asynchronous queue.

You can use the async queue to call `influxdb2` only once. Below is a sketch based on how I do thing this for Logstash. Note that I have not tested this sketch (sorry), but I think the same principles will apply for your use-case.

```clojure
;; Establish a dedicated queue and thread(s) for sending metrics to InfluxDB.
(let [influx-queue (async-queue!
                    :influx-output-queue {:queue-size 1000 :core-pool-size 1 :max-pool-size 1}
                    (influxdb2 {:host "influxdb.example.com"
                                :organization "riemann"
                                :bucket "riemann"
                                :token "riemann"}))]

  ;; We've now defined the queue. Importantly, we've done it only once, in the
  ;; let-binding. Now we can define a stream function that closes over the queue
  ;; so that we can send many events to the single queue instance.
  (defn send-to-influx
    "A stream for sending events to influx2 via an async queue."
    [& children]
    (fn [event]
      (call-rescue event (conj children influx-queue)))))
```

**Comment by node13h** [comment]
@jarpy thanks, but I've already got it wrapped in `async-queue!`. The VisualVM screenshots above were taken while `influxdb2` was wrapped in `async-queue!`. The problem is not in `influxdb2, but in `post-data` which keeps creating a new instances of `WriteApi` on each invocation.

My config:

```
influxdb-batch-sender (batch 100 1
    (async-queue! :agg {:queue-size 1000
                        :core-pool-size 2
                        :max-pool-size 16}
                  (influxdb2 influxdb-creds)))
```

**Comment by jarpy** [comment]
Ah! Thanks for explaining. I was making assumptions based on my own experience, not yours. Sorry for the trouble.
