### ISSUE TITLE
Database Support for DaMeng

### ISSUE THREAD

**Issue by visxu** [riemann/riemann#1043]
I'd like to confirm one thing: Does riemann support DaMeng database ?
DaMeng: https://www.dameng.com/

Thanks in advance for your checking.

**Comment by smortex** [comment]
There is no built-in support for this database.  The list of built-in forwarders is available in the API documentation: https://riemann.io/api.html

**Comment by visxu** [comment]
@smortex 
Well, okay. Thanks for your quick response.

**Comment by jamtur01** [comment]
We would welcome additional support if you're interested in working on it. The pattern for forwarders is pretty easy to see from the codebase.
