### ISSUE TITLE
Provide optional "sort" and "limit" parameters to query

### ISSUE THREAD

**Issue by eric** [riemann/riemann#125]
It would be nice, when querying the index, to be able to specify a sort order for events and a limit on the number of events that were returned.

**Comment by algernon** [comment]
Yeah, allowing limit at the end would be nice, but my brain hurts from all the antlr stuff. I'll revisit that a bit later. :)

**Comment by pyr** [comment]
@algernon should we keep this open or can we table it for now?

**Comment by algernon** [comment]
Feel free to close this, I don't see myself getting around to update this anytime soon. When I do, I have my branch.

**Comment by eric** [comment]
It's definitely something that I run into wanting quite a bit, but definitely agree there's a lot of things that need to happen to make it make sense holistically.

**Comment by pyr** [comment]
@eric agreed.
