### ISSUE TITLE
Documentation questions

### ISSUE THREAD

**Issue by judofyr** [riemann/riemann#146]
## Under "Find the host using the most CPU":

> You want to know which host is under the heaviest CPU load. The coalesce stream remembers the last events from each host and service, and sends them all as a vector to its children. We can map that vector of events to a single event--the one with the largest metric--using folds/maximum. Then we just set the service and host, since this event pertains to the system as a whole.
> 
> ``` clojure
> (coalesce (smap folds/maximum
>  (with {:service "Max CPU" :host nil} prn)))
> ```

Why do use use `smap` here and not `sreduce`? The documentation for smap says that it "Calls children with (f event)", but folds/maximum says it takes `events`, not `event`.
## Under "Report exceptions":

``` clojure
(where (service "exception")
  (with :metric 1
    (by :service
      (rate 10 index graph))))
```

I think you mean `(where (tagged "exception")`?
## TTL and the index

It's also a little unclear what data Riemann actually stores. It seems that every event is stored in the index for x seconds where x is the TTL of the event. Correct? But then there's this sentence:

> Events that sit in the index for longer than their TTL are removed from the index and reinserted into the event streams with state "expired".

What do you mean by "reinserted"? Now it sounds like the state is changed to "expired" (and the other fields are the same), but then it won't actually remove anything from the index, or?

I'm just a bit confused about what Riemann stores and for how long. Is it safe to send thousands of events per second with a 60s TTL, or would it take up lots of memory?

**Comment by freezhan** [comment]
Riemann store all event in memory if it is in TTL?

I don't clearly understand the index 

> If you send a thousand events with the same host and
service, the index's always contains only 1 event. 


If in 10 minutes, I send 2 event.
the first one is:
```json
{
    "host": "host1", 
    "service": "app", 
    "ttl": 600, 
    "metric": 500
}
```
the second one is:
```json
{
    "host": "host1", 
    "service": "app", 
    "ttl": 600, 
    "metric": 501
}
```
And then I want to alert XXX@example.com if the sum of metric is more than 1000 of last 10 minutes.
How to implement this?

```clojure
(stream		  
  (moving-time-window 600 ; 600 sec = 10 min		    	        	    
  (folds/sum		      
    (while (> metric 1000)		        
      (email "XXX@example.com")))))
```

### When I send the second event to Riemann, does the first one is auto remove from the memory?

> Depends on the stream. Some streams have unbounded memory use: for
example, rollup could hang on to a million events in an hour.
(moving-time-window 60) hangs on to the last 60 seconds worth of events.
