### ISSUE TITLE
Discussion: custom attributes support in query language

### ISSUE THREAD

**Issue by eric** [riemann/riemann#300]
I'm investigating supporting custom attributes in the query language and I wanted to get feedback on query syntaxes.

I'm leaning towards making [`field`](https://github.com/aphyr/riemann/blob/7da5cdbafd355b1454cd225d9e8fee28d6f763a4/src/riemann/Query.g#L75-L83) include [`ID`](https://github.com/aphyr/riemann/blob/7da5cdbafd355b1454cd225d9e8fee28d6f763a4/src/riemann/Query.g#L85-L86) so you would be able to say `pid = 1`.

An alternative would be to provide a separate `custom` or `field` identifier so it would be like `field pid = 1`.

@aphyr: Does this seem reasonable?

If so, the one issue I'm seeing with implementing it is I'm having trouble figuring out how to properly "tag" that in the `.g` file to make it unambiguous in the [AST evaluator](https://github.com/aphyr/riemann/blob/7da5cdbafd355b1454cd225d9e8fee28d6f763a4/src/riemann/query.clj#L42-L70).

**Comment by pyr** [comment]
Marking this as design for future reference and basis for a PR to implement the new behavior.

**Comment by faxm0dem** [comment]
I think the current syntax is just fine `myattr = "too" `
