### ISSUE TITLE
Integrating a plugin

### ISSUE THREAD

**Issue by thapliyalgunjan** [riemann/riemann#355]
Using riemann 0.2.4.1 on Redhat CentOs 6.5
Have this in my riemann-default

# Optionally add classes to the classpath for additional functionality
EXTRA_CLASSPATH=/my/esplugin/elastisch/trunk/src

# Optional JAVA_OPTS
# EXTRA_JAVA_OPTS=

In riemann.config

(:require [clojurewerkz.elastisch.native :as es])
(info "Required folder")

; -*- mode: clojure; -*-
; vim: filetype=clojure

(logging/init :file "riemann.log")

..........

On running

# java -jar riemann.jar
INFO [2014-04-07 08:34:11,656] main - riemann.bin - PID 9565

ERROR [2014-04-07 08:34:11,660] main - riemann.bin - Couldn't start
java.io.FileNotFoundException: Could not locate clojurewerkz/elastisch/native__init.class or clojurewerkz/elastisch/native.clj on classpath: 
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5018.invoke(core.clj:5530)
	at clojure.core$load.doInvoke(core.clj:5529)
	at clojure.lang.R

**Comment by AeroNotix** [comment]
The way you're supposed to add plugins to Riemann is to use the `load-plugin` function.

**Comment by pyr** [comment]
@thapliyalgunjan EXTRA_CLASSPATH will only be processed if you use the wrapper init script. Alternately, you can use the `(depend)` function which is documented in the API which will provide this functionality.
