### ISSUE TITLE
Debian init.d script swallows init errors

### ISSUE THREAD

**Issue by jmif** [riemann/riemann#459]
Because init errors (i.e. invalid config) are sent to STDOUT, the packaged init.d script doesn't output these errors by default.

**Comment by pguillebert** [comment]
On a related note, the .deb package also sets incorrect access rights on /var/log/riemann directory, it should be writable by the riemann user : I struggled a bit (because there was no errors) to find out my events couldn't be logged by riemann user...

**Comment by md5** [comment]
This was fixed in 53ca657b6f70172ca16613882eabac713bf6e08b, but that commit is not in a release yet.

**Comment by md5** [comment]
See #497

**Comment by md5** [comment]
The STDOUT issue was fixed in 104535e2b79530599c8315f830fc9f9d1b991c0c, which is included in 0.2.5 and later.

That being said, if you provide your own `riemann.config` that doesn't call `logging/init` with `/var/log/riemann/riemann.log`, then Riemann won't write there.

**Comment by pyr** [comment]
Can this considered fixed by #497?

**Comment by pyr** [comment]
Fixed in 0.2.11 AFAICT.
