### ISSUE TITLE
Prevent TLS renegotiation attacks

### ISSUE THREAD

**Issue by aphyr** [riemann/riemann#475]
The move to Netty 4 changed the option to disable TCP renegotiation and I haven't found out how to turn it off again. There's a TODO in transport/tcp.clj.

**Comment by benmoss** [comment]
https://github.com/netty/netty/commit/50fafdc3d32a67817050f011a39dd3e1bfbaac40 was the commit that removed it, it says 

```
- Removed enableRenegotiation property
  - JDK upgrade fixes the security vulnerability - no need to complicate
    our code
```

sooo problem solved? ¯\_(ツ)_/¯

**Comment by akwangho** [comment]
Hi,

It looks the renegotiation is still available for openJDK.
The version:
`bash
bash-4.1# java -version                                                                                                                                                                                                                      
`
`bash
java version "1.7.0_05-icedtea"                                                                                                                                                                                                              
`
`bash
OpenJDK Runtime Environment (rhel-2.2.1.el6_3.3-x86_64)                                                                                                                                                                                      
`
`bash
OpenJDK 64-Bit Server VM (build 23.0-b21, mixed mode)
`
Any approach to disable renegotiation in netty?

**Comment by benmoss** [comment]
I don't think so, and this probably isn't the right place to be asking either.

**Comment by brettwooldridge** [comment]
@benmoss Executing the sslyze tool against my netty server (4.0.23-Final), running on Oracle Java 8 (1.8.0_11) on Windows 7, it is reporting:
```
* Session Renegotiation:
    Client-initiated Renegotiations:   VULNERABLE - Server honors client-initiated renegotiations
    Secure Renegotiation:              OK - Supported
```
As noted above, there appears to be no way in the current codebase to disable this and even current JDK versions do not appear to address this.

Why was this removed?

**Comment by benmoss** [comment]
@brettwooldridge because the API that was exposed by netty was removed. The commit in netty linked above removed it, with the comment that I mentioned that claimed that the problem was resolved at the JDK level. For completeness' sake, this is the commit to riemann that upgraded netty: https://github.com/aphyr/riemann/commit/bc019601b02b712329dc9513e59106610eadeabd#diff-596d412792aaf39683c703e8433785efL186

I'm not sure what should be done. File an issue with netty? Understand how any server using netty fixes this vulnerability and apply that here?

**Comment by benmoss** [comment]
Actually it looks to my untrained eye that [netty 4.0.28](http://netty.io/news/2015/05/07/4-0-28-Final.html) included a fix for disabling client renegotiation: https://github.com/netty/netty/pull/3750

Perhaps @brettwooldridge you could try upgrading riemann's version and see if that fixes the sslyze warning?
