### ISSUE TITLE
UDP issue in 0.2.7

### ISSUE THREAD

**Issue by dbriones** [riemann/riemann#488]
Hi folks, 

Now that I’ve [got the TCP server working](https://github.com/aphyr/riemann/pull/487), I’ve run into a new problem that also seems to be related to the Netty upgrade:

We are using Logstash to forward error-level log events to Riemann over UDP. Some of the log events are pretty big, as they can include stack traces and other arbitrarily long data we use to diagnose issues in our system.

Unfortunately, after the 0.2.7 upgrade, I’m getting a lot of Riemann errors like the one below. I took a look at the UDP server in Riemann and noticed [the big note about `max-size`](https://github.com/aphyr/riemann/blob/bc019601b02b712329dc9513e59106610eadeabd/src/riemann/transport/udp.clj#L126), as well as [the default setting of 16k](https://github.com/aphyr/riemann/blob/bc019601b02b712329dc9513e59106610eadeabd/src/riemann/transport/udp.clj#L143). However, I’m a bit confused, because despite the fact that [that note predates 0.2.7](https://github.com/aphyr/riemann/blame/bc019601b02b712329dc9513e59106610eadeabd/src/riemann/transport/udp.clj#L126), our setup works just fine on 0.2.6. 

I tried increasing `max-size` to no avail. I’m currently looking at the Netty code to see if I can figure out why 3.8.0 behaves differently than 4.0.21, but I feel like I might be going a bit further down the rabbit hole than I’d like.

I’m reverting to 0.2.6 for now. The other workaround I thought of was to use TCP instead. That probably won’t be a problem as long as we're *only* sending error-level events, but we had been planning to eliminate Logstash and send *all* of our log events to Riemann directly. I’m a little worried that changing to TCP might make that more difficult.

Help?

----

```
WARN [2015-01-09 20:13:09,508] defaultEventExecutorGroup-2-1 - riemann.transport.udp - UDP handler caught
io.netty.handler.codec.DecoderException: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
...
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.
        at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:70)
        at com.google.protobuf.CodedInputStream.pushLimit(CodedInputStream.java:651)
        at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:307)
        at com.aphyr.riemann.Proto$Msg.<init>(Proto.java:3931)
        at com.aphyr.riemann.Proto$Msg.<init>(Proto.java:3847)
        at com.aphyr.riemann.Proto$Msg$1.parsePartialFrom(Proto.java:3970)
        at com.aphyr.riemann.Proto$Msg$1.parsePartialFrom(Proto.java:3965)
        at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:141)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:176)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:182)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
        at io.netty.handler.codec.protobuf.ProtobufDecoder.decode(ProtobufDecoder.java:119)
        at io.netty.handler.codec.protobuf.ProtobufDecoder.decode(ProtobufDecoder.java:63)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
        ... 15 more
```

**Comment by dbriones** [comment]
@udoprog I noticed you created the PR for the Netty upgrade... any thoughts?

**Comment by aphyr** [comment]
On 01/09/2015 04:58 PM, Dante Briones wrote:
> Hi folks,
>
> Now that I’ve got the TCP server working
> <https://github.com/aphyr/riemann/pull/487>, I’ve run into a new problem that
> also seems to be related to the Netty upgrade:
>
> We are using Logstash to forward error-level log events to Riemann over UDP.
> Some of the log events are pretty big, as they can include stack traces and
> other arbitrarily long data we use to diagnose issues in our system.
>
> Unfortunately, after the 0.2.7 upgrade, I’m getting a lot of Riemann errors like
> the one below. I took a look at the UDP server in Riemann and noticed the big
> note about |max-size|
> <https://github.com/aphyr/riemann/blob/bc019601b02b712329dc9513e59106610eadeabd/src/riemann/transport/udp.clj#L126>,
> as well as the default setting of 16k
> <https://github.com/aphyr/riemann/blob/bc019601b02b712329dc9513e59106610eadeabd/src/riemann/transport/udp.clj#L143>.
> However, I’m a bit confused, because despite the fact that that note predates
> 0.2.7
> <https://github.com/aphyr/riemann/blame/bc019601b02b712329dc9513e59106610eadeabd/src/riemann/transport/udp.clj#L126>,
> our setup works just fine on 0.2.6.

I should note that your network, OS, etc are under no obligation to deliver 
these messages at all, or, as you've discovered, correctly. *Please please 
please* use TCP everywhere, unless you really know what you're doing.

That said, this may be a bug (we may be failing to set the recv buffer 
correctly) or may be "the netty buffer size actually means something now". I'd 
try to dump those packets and see if you're maxing out at 16K, and if so, try 
raising the limit.

--Kyle

**Comment by dbriones** [comment]
Thanks for the (really quick!) feedback, Kyle! 

I'm going to be traveling most of the week, but I'll take a look into this when I have a chance.

**Comment by udoprog** [comment]
I didn't look deep into this, and I did not attempt to verify the UDP implementation either.

You should inspect the error counter in your OS of choice (preferrably Linux, in which it would be ```netstat -su```) and see if it grows significantly at the time you are expecting the events.

As for the partial events, I must agree with @aphyr, the OS is at liberty to drop or truncate your datagrams when using UDP. That this happened from this upgrade (probably due to some configuration change) should be taken as an indication to switch.

**Comment by aphyr** [comment]
(it actually could also be that we're not setting the UDP recv buffer size correctly any more, or that we *are* setting it correctly now and it defaulted to a larger value before, etc etc.)

**Comment by udoprog** [comment]
@aphyr Certainly, it should be noted that setting ```SO_RCVBUF``` reliably can be a challenge due to varying ```net.core.rmem_max``` values from dist to dist.

I've recently encountered that an upgrade from a pre 3.0 kernel disallowed the setting of ```SO_RCVBUF``` with ```SO_RCVBUFFORCE``` above ```net.core.rmem_max```, even with ```CAP_NET_ADMIN``` (i.e. running as root).
