### ISSUE TITLE
rollup on slack does not show event details

### ISSUE THREAD

**Issue by joelapatatechaude** [riemann/riemann#510]
When trying to use rollup with slack with this type of code:
```clojure
(streams
 (where (service "proc:meminfo:MemFree")
        (where (> metric memfree_tresh)
               (rollup 1 60 slacker_rollup))))
```
the events on slack have no details:
>Riemann rollupbot 4:03 PM Host:  State:  Description:  Metric:

Note that without the rollow slacks shows the event details:
```clojure
(streams
 (where (service "proc:meminfo:MemFree")
        (where (> metric memfree_tresh)
               slacker_rollup)))
```
>Riemann rollupbot 4:06 PM Host: test.cluster State:  Description:  Metric: 65088

**Comment by joelapatatechaude** [comment]
throttle seems to display the event details on the other hand.

**Comment by andrestc** [comment]
I'm also having this issue. Did you manage to fix it?

**Comment by scratch-net** [comment]
Could this please be fixed? +1

**Comment by pyr** [comment]
the slack client does not know how to deal with sequences of events, which is why on rollup, the messages are not formatted correctly.

**Comment by pyr** [comment]
You can provide your own formatter which can test for `(sequential? events)` and act accordingly by using the `:formatter` key when creating the slack client.

As an example you could use the following formatter:

```
(defn my-slack-formatter [events]
  (if (sequential? events)
      {:attachments [{:fields [{:title "riemann events" :short true :value (str (count events))}
                                          {:title "riemann hosts" :short true :value (str (count (group-by :host events)))}]}]}
      (default-formatter events)))
```

**Comment by blalor** [comment]
Is there an open issue to fix the default formatter?
