### ISSUE TITLE
Enhancement: RPM init scripts return proper errors when startup fails (but not reload)

### ISSUE THREAD

**Issue by faxm0dem** [riemann/riemann#524]
This entry in the 0.2.9 changelog gave me an idea: wouldn't it be cool to have the same for reloads?
I was thinking about writing a return code to a file, or something.

**Comment by aphyr** [comment]
The blocking semantics might be tough. What about tailing the logfile?

**Comment by faxm0dem** [comment]
that was of course the last resort ;)

**Comment by pyr** [comment]
closing this for now, hoping to see it reopened as a PR :-)
