### ISSUE TITLE
Riemann testing gives unexpected output

### ISSUE THREAD

**Issue by kgxsz** [riemann/riemann#552]
We're attempting to write a set of small tests for individual streams. In the example below, we want a couple of tests for "my-stream" and "my-other-stream", so we inject directly to these with some input and assert on expected output. These tests pass as expected. We also want to do an end-to-end test that injects on all streams. When we add the 'end-to-end' test, we get a failure, saying that 'service-one-rate-of-change-is-measured' test expects `[{:service "service-1", :time 0, :host "host-1", :metric 1} {:service "service-1", :time 10, :host "host-1", :metric 1}]`.

We assume that each deftest is giving us a "clean slate", but it appears this isn't the case - by adding the last test, we are causing a failure in another test. Are we missing something in our reasoning? How can we ensure that each deftest sets up a new and isolated test run?

Cheers.

```clojure
(def my-stream
  (where (service "service-2")
    (tap :tap-service-2
      (coalesce 10
        (tap :tap-coalesce #(info %))))))

(def my-other-stream
  (where (service "service-1")
      (tap :tap-service-1
        (ddt
          (tap :tap-ddt #(info %))))))

(streams
  my-other-stream
  my-stream)

(tests
  (deftest my-test
    (let [result (inject!
                   [riemann.config/my-stream]
                   [{:host "host-1" :service "service-2" :time 0 :metric 100}
                    {:host "host-1" :service "service-2" :time 1 :metric 200}])]
      (is (= [[ {:host "host-1" :service "service-2" :time 0 :metric 100} ]]
             (:tap-coalesce result)))))

  (deftest streams-are-filtered-by-service
    (let [result (inject!
                   [riemann.config/my-other-stream]
                   [{:host "host-1" :service "service-1" :time 0 :metric 100}
                    {:host "host-1" :service "service-2" :time 1 :metric 200}])]
      (is (= [{:host "host-1" :service "service-1" :time 0 :metric 100}]
             (:tap-service-1 result)))))

  (deftest service-one-rate-of-change-is-measured
    (let [result (inject!
                   [riemann.config/my-other-stream]
                   [{:host "host-1" :service "service-1" :time 0 :metric 20}
                    {:host "host-1" :service "service-1" :time 10 :metric 30}])]
      (is (= [{:host "host-1" :service "service-1" :time 10 :metric 1}]
             (:tap-ddt result)))))

  (deftest end-to-end
    (let [result (inject!
                   [{:host "host-1" :service "service-1" :time 0 :metric 20}
                    {:host "host-1" :service "service-1" :time 10 :metric 30}])]
      (is (= [{:host "host-1" :service "service-1" :time 10 :metric 1}]
             (:tap-ddt result))))))
```

**Comment by aphyr** [comment]
You'll have to redesign the test system to create fresh copies of the config every time. Riemann.test only knows how to clear the config and scheduler right now; it can't (as presently written) force you to abandon state already squirreled away in streams. Sorry, was trying to get an 80% soln out the door for folks with limited time. :-(
On Apr 27, 2015 6:44 AM, Keigo Suzukawa <notifications@github.com> wrote:We're attempting to write a set of small tests for individual streams. In the example below, we want a couple of tests for "my-stream" and "my-other-stream", so we inject directly to these with some input and assert on expected output. These tests pass as expected. We also want to do an end-to-end test that injects on all streams. When we add the 'end-to-end' test, we get a failure, saying that 'service-one-rate-of-change-is-measured' test expects [{:service "service-1", :time 0, :host "host-1", :metric 1} {:service "service-1", :time 10, :host "host-1", :metric 1}].

We assume that each deftest is giving us a "clean slate", but it appears this isn't the case - by adding the last test, we are causing a failure in another test. Are we missing something in our reasoning? How can we ensure that each deftest sets up a new and isolated test run?

Cheers.

(def my-stream
  (where (service "service-2")
    (tap :tap-service-2
      (coalesce 10
        (tap :tap-coalesce #(info %))))))

(def my-other-stream
  (where (service "service-1")
      (tap :tap-service-1
        (ddt
          (tap :tap-ddt #(info %))))))

(streams
  my-other-stream
  my-stream)

(tests
  (deftest my-test
    (let [result (inject!
                   [riemann.config/my-stream]
                   [{:host "host-1" :service "service-2" :time 0 :metric 100}
                    {:host "host-1" :service "service-2" :time 1 :metric 200}])]
      (is (= [[ {:host "host-1" :service "service-2" :time 0 :metric 100} ]]
             (:tap-coalesce result)))))

  (deftest streams-are-filtered-by-service
    (let [result (inject!
                   [riemann.config/my-other-stream]
                   [{:host "host-1" :service "service-1" :time 0 :metric 100}
                    {:host "host-1" :service "service-2" :time 1 :metric 200}])]
      (is (= [{:host "host-1" :service "service-1" :time 0 :metric 100}]
             (:tap-service-1 result)))))

  (deftest service-one-rate-of-change-is-measured
    (let [result (inject!
                   [riemann.config/my-other-stream]
                   [{:host "host-1" :service "service-1" :time 0 :metric 20}
                    {:host "host-1" :service "service-1" :time 10 :metric 30}])]
      (is (= [{:host "host-1" :service "service-1" :time 10 :metric 1}]
             (:tap-ddt result)))))

  (deftest end-to-end
    (let [result (inject!
                   [{:host "host-1" :service "service-1" :time 0 :metric 20}
                    {:host "host-1" :service "service-1" :time 10 :metric 30}])]
      (is (= [{:host "host-1" :service "service-1" :time 10 :metric 1}]
             (:tap-ddt result))))))

**Comment by Farhie** [comment]
Thanks for the update @aphyr

**Comment by kgxsz** [comment]
Okay. Cheers @aphyr. In any case, thanks for all the fantastic work on this, we've been having a blast working with Riemann.
