### ISSUE TITLE
Trouble with fixed time window

### ISSUE THREAD

**Issue by timterry** [riemann/riemann#558]
Hi,

I'm having trouble getting the fixed time window to work. It seems to never trigger pagerduty I'm trying the following code:
````
(fixed-time-window 120
  (smap (fn [events]
    (where (> 10 (count events))
      (:trigger pagerduty)))))
````
(trigger pagerduty if more than 10 events in 2 minutes.)

I've tried echo'ing events outside of the fixed time window and they are logged fine, however when i add echo statements to the where or smap function none are printed. If i remove the fixed time window then events are sent directly to pagerduty fine. 

Any ideas what could be wrong? i tried decreasing the window size and sending more events through with echo statements in various places. Is there an alternative way to debug the riemann config instead of adding echo statements?

Thanks

Tim

**Comment by aphyr** [comment]
On 05/28/2015 07:50 AM, timterry wrote:
> Hi,
>
> I'm having trouble getting the fixed time window to work. It seems to never
> trigger pagerduty I'm trying the following code:

   ; With vectors of up to 120 events
> (fixed-time-window 120
      ; Take each vector; let it be `events`, and
>    (smap (fn [events]
        ; Construct and return a `where` stream without passing it any events
>      (where (> 10 (count events))
          ; Never reached--we never invoke the function (where ...) returns.
>        (:trigger pagerduty)))))

Easy enough fix: just drop the `smap`. `where` can act directly on the output of 
`fixed-time-window`.

--Kyle
