### ISSUE TITLE
querying the index stalls with numeric custom attributes

### ISSUE THREAD

**Issue by mfournier** [riemann/riemann#564]
I noticed that querying the index never returns when one of the queried events
contains a numeric value in a custom attribute (using 0.2.9, didn't try other
versions).

Here's a simple config which reproduces the problem:
```
(logging/init {:file "riemann.log" :console true})

(tcp-server)
(udp-server)

(let [index (index)]
  (streams
    (where (service "ok") index)
    (where (service "not ok") (with :some_attribute 123 index))))
```

```
[53] pry(main)> r << { :host => 'test', :service => 'ok', :ttl => 300 }
=> nil
[54] pry(main)> r << { :host => 'test', :service => 'not ok', :ttl => 300 }
=> nil
[55] pry(main)> r['service = "ok"']
=> [<Riemann::Event time: 1434432035, service: "ok", host: "test", ttl: 300.0>]
[56] pry(main)> r['service = "not ok"']
Riemann::Client::TcpSocket::Timeout: Could not read from 127.0.0.1:5555 in 5 seconds
from /usr/lib/ruby/vendor_ruby/riemann/client/tcp_socket.rb:300:in `rescue in readpartial'
[57] pry(main)> r['true']
Riemann::Client::TcpSocket::Timeout: Could not read from 127.0.0.1:5555 in 5 seconds
from /usr/lib/ruby/vendor_ruby/riemann/client/tcp_socket.rb:300:in `rescue in readpartial'
```

The 5 second timeout is the default from the ruby `riemann/client` lib. I also
see this behaviour using `riemann-c-client`, which rules out a problem on the
client side.

Subscribing to a websocket stream of such events works fine, as well as using
these numeric attributes from within the streams DSL. It's really just querying
the index.

I'm aware custom attributes are expected to be strings, but I don't think
blocking without any error message is the best feedback in such case ;)

Ideally these would be silently casted to strings before getting indexed or at
reception time. But this case should IMHO at least get caught and raise an
error rather than blocking.

Thanks !

**Comment by faxm0dem** [comment]
:+1: I had experience this earlier

**Comment by pyr** [comment]
The protobuf definition of attributes is indeed a map of string to string, I'll see if we can guard the behavior in the conversion code.

**Comment by pyr** [comment]
@mfournier @faxm0dem this will be part of the next release.

**Comment by mfournier** [comment]
Awesome, thanks @pyr !

**Comment by faxm0dem** [comment]
a little late, but WFM!
