### ISSUE TITLE
How to start Riemann in Windows 7

### ISSUE THREAD

**Issue by Rajeshkumar123** [riemann/riemann#570]
I am looking for detailed document for configuring Riemann in windows . I am newbie to Riemann I am looking for any procedure or description explaining about starting riemann service in windows.

**Comment by aphyr** [comment]
There aren't very many folks running Riemann under Windows, but I do get occasional patches so I think it's possible. As for services, you'll have to figure that one out on your own--I presume anything that can run a Java process as a Windows service should do. If you'd like to contribute windows packaging back to core, feel free to make a PR. :)

**Comment by Rajeshkumar123** [comment]
Will your current release work under windows because I couldn't find any bin folder .

**Comment by pyr** [comment]
@Rajeshkumar123 to run riemann on windows, you'll have to start the JAR directly, we don't plan on releasing installers at the moment.
