### ISSUE TITLE
java.lang.IllegalArgumentException: Level cannot be null or an empty String when using nagios export

### ISSUE THREAD

**Issue by jersten** [riemann/riemann#589]
The full stacktrace is below:

```
#riemann.codec.Event{:host "ip-10-0-1-209", :service "riemann streams rate", :state nil, :description nil, :metric 0.0, :tags ["riemann"], :time 1438616659649/1000, :ttl 20}
WARN [2015-08-03 15:44:19,650] Thread-7 - riemann.core - instrumentation service caught
java.lang.IllegalArgumentException: Level cannot be null or an empty String
        at com.googlecode.jsendnsca.core.utils.LevelUtils.getLevel(LevelUtils.java:38)
        at clj_nsca.core$nagios_message.invoke(core.clj:29)
        at riemann.nagios$event__GT_nagios.invoke(nagios.clj:15)
        at riemann.nagios$nagios$fn__10767.invoke(nagios.clj:36)
        at riemann.core$stream_BANG_$fn__5727.invoke(core.clj:19)
        at riemann.core$stream_BANG_.invoke(core.clj:18)
        at riemann.core$instrumentation_service$measure__5736.invoke(core.clj:57)
        at riemann.service.ThreadService$thread_service_runner__3283$fn__3284.invoke(service.clj:71)
        at riemann.service.ThreadService$thread_service_runner__3283.invoke(service.clj:70)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:745)
```

I am testing on Amazon Linux AMI with the RPM from riemann.io website. I installed `riemann-tools` and executed it from the command-line.

My configuration file is as follows:

```
; -*- mode: clojure; -*-
; vim: filetype=clojure

(logging/init {:file "/var/log/riemann/riemann.log"})

; Listen on the local interface over TCP (5555), UDP (5555), and websockets
; (5556)
(let [host "127.0.0.1"]
  (tcp-server {:host host})
  (udp-server {:host host})
  (ws-server  {:host host}))

; Expire old events from the index every 5 seconds.
(periodically-expire 5)

(let [index (index)]
  ; Inbound events will be passed to these streams:
  (streams
    prn
    
    (nagios {:host "localhost" :port 5667 :password "nagios" } )

    (default :ttl 60
      ; Index all events immediately.
      index

      ; Log expired events.
      (expired
        (fn [event] (info "expired" event))))))
```

**Comment by aphyr** [comment]
>        at riemann.nagios$event__GT_nagios.invoke(nagios.clj:15)

Looks like Nagios expected a level and didn't get one. Take a look at the events you're sending to Nagios? Maybe it wasn't expecting an expired event?

**Comment by nopejpg** [comment]
@aphyr I'm just running `riemann-health` by itself.

**Comment by nopejpg** [comment]
Actually, I'm able to reproduce this error without sending any events to riemann; all I have to do is start it up; see:

```
# riemann 
INFO [2015-08-03 16:36:26,153] main - riemann.bin - PID 2541
INFO [2015-08-03 16:36:26,285] clojure-agent-send-off-pool-3 - riemann.transport.websockets - Websockets server 127.0.0.1 5556 online
INFO [2015-08-03 16:36:26,318] clojure-agent-send-off-pool-0 - riemann.transport.tcp - TCP server 127.0.0.1 5555 online
INFO [2015-08-03 16:36:26,334] clojure-agent-send-off-pool-3 - riemann.transport.udp - UDP server 127.0.0.1 5555 16384 -1 online
INFO [2015-08-03 16:36:26,335] main - riemann.core - Hyperspace core online
#riemann.codec.Event{:host "ip-10-0-1-209", :service "riemann streams rate", :state nil, :description nil, :metric 0.0, :tags ["riemann"], :time 719309898131/500, :ttl 20}
WARN [2015-08-03 16:36:36,358] Thread-7 - riemann.core - instrumentation service caught
java.lang.IllegalArgumentException: Level cannot be null or an empty String
        at com.googlecode.jsendnsca.core.utils.LevelUtils.getLevel(LevelUtils.java:38)
        at clj_nsca.core$nagios_message.invoke(core.clj:29)
        at riemann.nagios$event__GT_nagios.invoke(nagios.clj:15)
        at riemann.nagios$nagios$fn__10767.invoke(nagios.clj:36)
        at riemann.core$stream_BANG_$fn__5727.invoke(core.clj:19)
        at riemann.core$stream_BANG_.invoke(core.clj:18)
        at riemann.core$instrumentation_service$measure__5736.invoke(core.clj:57)
        at riemann.service.ThreadService$thread_service_runner__3283$fn__3284.invoke(service.clj:71)
        at riemann.service.ThreadService$thread_service_runner__3283.invoke(service.clj:70)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:745)
```

The errors occur every 10 seconds.

**Comment by aphyr** [comment]
Again, you're probably sending events to Nagios that the Nagios adapter doesn't know how to handle. Every 10 seconds suggests the Riemann instrumentation events. I didn't write the Nagios adapter so I'm not sure exactly how level works, but that error message suggests where in the code to look!

**Comment by nopejpg** [comment]
But, I'm not even sending events? I just enabled it in the configuration and it's throwing those errors.

**Comment by aphyr** [comment]
Riemann generates [internal instrumentation events](http://riemann.io/howto.html#measure-riemann-itself). You probably want to select only some events to send to Nagios, or transform events appropriately before sending them on.

**Comment by nopejpg** [comment]
I'm able to disable the stacktraces by adding `(instrumentation {:enabled? false})` into the configuration. But, that really isn't a solution; it seems to be a work around.

**Comment by jamtur01** [comment]
@nopejpg The solution is looking at how the Nagios plugin processes events and work out what it's choking on - I presume setting a default for the level or stopping it faulting on a nil level.

**Comment by nopejpg** [comment]
Shouldn't the nagios export add a default if there isn't one though? I mean, shouldn't it set sane defaults rather than assuming what it was given is OK?

**Comment by aphyr** [comment]
(I agree that it'd probably be sensible for the Nagios plugin to apply some kind of defaults)

**Comment by bfritz** [comment]
@nopejpg Following the breadcrumbs a bit here...  Looks like the [nagios ouput](https://github.com/aphyr/riemann/blob/master/src/riemann/nagios.clj) uses clj-nsca (both by @bracki).  clj-nsca wraps jsendnsca which [hardcodes 4 states](https://code.google.com/p/jsendnsca/source/browse/tags/1.1.1/jsendnsca-core/src/main/java/com/googlecode/jsendnsca/core/utils/LevelUtils.java#17): `ok`, `warning`, `critical` and `unknown`.

A PR to nagios.clj that maps the nil state to "unknown" might be a good solution.

**Comment by jamtur01** [comment]
@bfritz Beat me to it. Just did exactly the same digging. :)
