### ISSUE TITLE
Sending a UnixNano timestamp causes IntOverflow in InfluxDB

### ISSUE THREAD

**Issue by bg451** [riemann/riemann#600]
Sending a unix timestamp that counts the nanoseconds since the epoch causes an integer overflow when using `riemann.common/unix-to-iso8601`. I'm using Go, so sending stuff over as a UnixNano timestamp is pretty common and influxdb 0.9 defaults to nanosecond precision, it'd be nice to support unix nano. There was also a small issue where a bunch of our events had the same data in it, but because we were sending a couple thousand events a second and being written to influx, a bunch would have the same timestamp due to the lack of precision, thus overwriting each other.

 Made a patch to fix this, going to make a PR right now.

**Comment by pyr** [comment]
Hi @bg451 we are not considering moving time to nanoseconds at the moment.
