### ISSUE TITLE
Make sure or document that commas fail in InfluxDB 0.9

### ISSUE THREAD

**Issue by peterneubauer** [riemann/riemann#602]
Make sure though either 

    (adjust #(assoc % :service (clojure.string/replace (:service %) "," "_"))
      

or document that e.g. `kafka.server:name=MessagesInPerSec,topic=xxx,type=BrokerTopicMetrics.OneMinuteRate` is not working, but `kafka.server:name=MessagesInPerSec_topic=xxx_type=BrokerTopicMetrics.OneMinuteRate`, probably because commas will be treated indicating tags here.

**Comment by jwilder** [comment]
If you're writing to InfluxDB using the line protocol, commas and spaces need to be escaped with `\` if they are part of the measurement name.  Commas, spaces and equals need to be escaped with `\` if they are part of a tag key or tag value.

If you want your measurement to be
```
kafka.server:name=MessagesInPerSec,topic=xxx,type=BrokerTopicMetrics.OneMinuteRate
```

It should be sent it as: 

```
kafka.server:name=MessagesInPerSec\,topic=xxx\,type=BrokerTopicMetrics.OneMinuteRate
```

```
> insert kafka.server:name=MessagesInPerSec,topic=xxx,type=BrokerTopicMetrics.OneMinuteRate value=1
> show measurements
name: measurements
------------------
name
kafka.server:name=MessagesInPerSec

> insert kafka.server:name=MessagesInPerSec\,topic=xxx\,type=BrokerTopicMetrics.OneMinuteRate value=1
> show measurements
name: measurements
------------------
name
kafka.server:name=MessagesInPerSec
kafka.server:name=MessagesInPerSec,topic=xxx,type=BrokerTopicMetrics.OneMinuteRate

```

**Comment by pyr** [comment]
thanks for the precisions @jwilder
