### ISSUE TITLE
InfluxDB client problems?

### ISSUE THREAD

**Issue by tomeucapo** [riemann/riemann#605]

**Comment by jchauncey** [comment]
its not working for me. i will write the measurement name but nothing else. From the code I have no idea how its writing the value. It also should convert anything in the tags field to an influxdb tag but that doesnt happen either.

**Comment by royalaid** [comment]
I would like to add to this. It seems there is a problem if any of the fields contain values with a newchar in them. `riemann.influxdb/lineprotocol-encode-9` uses `replace-disallowed-9` to escape the characters but newline isn't included in that. As a result the if the field contains a newline it breaks the line-protocol and forwards akward looking data to influx

**Comment by pyr** [comment]
This is a bit too scarce information to act upon, I'll leave it up to @tomeucapo to reopen an issue with a more specific issue, cheers!
