### ISSUE TITLE
Trap SNMP events in riemann

### ISSUE THREAD

**Issue by qnick** [riemann/riemann#613]
At 2013 @aphyr [wrote](http://logs.lazybot.org/irc.freenode.net/%23riemann/2013-04-02.txt) "there could be an snmp server". Is there any chance to see it?
What should I do to send snmp traps into riemann server?

**Comment by aphyr** [comment]
Traps... Dunno if anyone has done that yet. Google reports several SNMP pollers though.
On Oct 9, 2015 7:36 AM, qnick <notifications@github.com> wrote:At 2013 @aphyr wrote "there could be an snmp server". Is there any chance to see it?
What should I do to send snmp traps into riemann server?

**Comment by bfritz** [comment]
@qnick Haven't seen anything like that published, but I suspect you could build a [snmp4j](http://www.snmp4j.org/) trap listener, something like [this](https://github.com/mchopker/myprojects/blob/master/TranSenderReceiver/src/SNMPTrapReceiver.java), and wrap it with a bit of clojure that converts the trap into a Riemann event.  The [graphite transport](https://github.com/aphyr/riemann/blob/0.2.10/src/riemann/transport/graphite.clj#L59) has an example of creating and event.

**Comment by pyr** [comment]
The collectd snmp plugin will emit events on traps (and will also poll if you want)

On October 9, 2015 5:41:43 PM CEST, Kyle Kingsbury <notifications@github.com> wrote:
>Traps... Dunno if anyone has done that yet. Google reports several SNMP
>pollers though.
>On Oct 9, 2015 7:36 AM, qnick <notifications@github.com> wrote:At 2013
>@aphyr wrote "there could be an snmp server". Is there any chance to
>see it?
>What should I do to send snmp traps into riemann server?
>
>—Reply to this email directly or view it on GitHub.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/aphyr/riemann/issues/613#issuecomment-146906805

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by faxm0dem** [comment]
Other idea: using snmptrapd and syslog-ng

**Comment by pyr** [comment]
Yes, that would be the most elegant and low-maintenance way.

On October 9, 2015 9:05:51 PM CEST, Fabien Wernli <notifications@github.com> wrote:
>Other idea: using snmptrapd and syslog-ng
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/aphyr/riemann/issues/613#issuecomment-146962800

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by qnick** [comment]
Ok, thank you. I decide to write python script for redirecting events from snmptrapd to riemann.
```python
#!/usr/bin/env python

import sys
import logging
from riemann_client.transport import UDPTransport
from riemann_client.client import QueuedClient
logging.basicConfig(filename='/tmp/snmp.log', level=logging.INFO)
tags = ["snmp"]
ttl = 120

host = raw_input()
ip = raw_input()

with QueuedClient(UDPTransport("localhost", 5555)) as client:
  for line in sys.stdin:
    logging.debug(line)
    oid , val = line.split(None,1)
    try:
      val = val.strip().strip('"')
      client.event(service = oid, metric_f = float(val), host = host, tags = tags, ttl = ttl)
    except ValueError:
      logging.warn("Cannot convert %s to float", val)
  client.flush()
```
It seems to work well.

**Comment by faxm0dem** [comment]
@pyr how do you configure collectd-snmp to listen for traps?

**Comment by pyr** [comment]
@faxm0dem turns out you can't
closing this as a solution was found.
