### ISSUE TITLE
moving-time-window suspected in affecting riemann server performance over time 

### ISSUE THREAD

**Issue by alecnmk** [riemann/riemann#622]
I've recently added moving-time-window aggregation in my riemann config: 

```clojure
(match :service #"^c.app."
    (by [:host :service]
       (moving-time-window (* 24 60 60)
          (smap folds/sum
            (adjust [:service str ".24h"]
                (throttle 1 10
                  influxdb-batched))))))
```

That piece of config supposed to aggregate events by host and service within recent 24h and sum it up to a single event and push it through a throttled stream once in 10 seconds to influxdb database.  

After that I've started experiencing strange behaviour: 
![grafana_-_riemann](https://cloud.githubusercontent.com/assets/166260/11021474/b589a22a-864a-11e5-83dd-addcc57368b8.jpg)

Stream latencies start to grow over time. At some point riemann server just hangs, stops processing any events with nothing suspicious in the logfile. Memory and CPU usage is ok. Stream rates are 100-200 events/sec in average without big spikes. 

I didn't look into the source code of the moving-time-window function yet. It's ok with me to just comment out that part of config for now. I'll try to dig into it once I have a chance. But maybe, just maybe there is something obvious somebody could think of just by looking at that graph and my config. Or maybe somebody is experiencing same behaviour and having trouble with localizing it. 

Env: 
```
Riemann 0.2.10

java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
```

**Comment by aphyr** [comment]
So 200 hz over 24 hours is about 17 million events you're holding on to in various buffers... And you have to pass over some fraction of those 17 million events 200 times a second... I'm not at all surprised this is slow. I suggest using a constant-space algorithm like (rate) and smoothing it with something like (ewma) if you want a longer input period, or at least using a fixed window to cut down on the n^2 time complexity.
On Nov 8, 2015 11:15 AM, Alexander Naumenko <notifications@github.com> wrote:I've recently added moving-time-window aggregation in my riemann config: 

(match :service #"^c.app."
    (by [:host :service]
       (moving-time-window (* 24 60 60)
          (smap folds/sum
            (adjust [:service str ".24h"]
                (throttle 1 10
                  influxdb-batched))))))

That piece of config supposed to aggregate events by host and service within recent 24h and sum it up to a single event and push it through a throttled stream once in 10 seconds to influxdb database.  

After that I've started experiencing strange behaviour: 


Stream latencies start to grow over time. At some point riemann server just hangs, stops processing any events with nothing suspicious in the logfile. Memory and CPU usage is ok. Stream rates are 100-200 events/sec in average without big spikes. 

I didn't look into the source code of the moving-time-window function yet. It's ok with me to just comment out that part of config for now. I'll try to dig into it once I have a chance. But maybe, just maybe there is something obvious somebody could think of just by looking at that graph and my config. Or maybe somebody is experiencing same behaviour and having trouble with localizing it.

**Comment by alecnmk** [comment]
Thanks Kyle, that makes sense!

So that's definitely not a bug or malfunction of Riemann. I didn't see internals of the function (my bad, should have check it first before opening new issue). It's just a bad use of that function by me. It might be worth to add a warning note to the documentation. I assume that could be a common use case (recent 24hour aggregation). And that function makes a good candidate for solving it for newbie with Riemann.

**Comment by jamtur01** [comment]
@alecnmk - https://github.com/aphyr/riemann/blob/gh-pages/howto.html and http://riemann.io/howto.html#group-events-in-time. That whole section could do with some solid examples.

**Comment by alecnmk** [comment]
@jamtur01 That's true, James. But that specific section with time grouping functions lacks usage examples. And that thing with my case. Imagine someone is using it for some critical setup. And the root of the problem is not obvious. It's hard to debug such long-playing issue under production load. Simple note about extreme use cases that show good and bad usage examples could save lots of time to Riemann users. I've seen such kind of notes to other functions within Riemann doc.

**Comment by jamtur01** [comment]
@alecnmk That's what I am suggesting you write and pointing out the place for it! :)

**Comment by alecnmk** [comment]
@jamtur01 oh, sure! will do! I could add 'bad use example' now.. but I'll try some workarounds to that use case to provide 'good use example' and then create a pull request to the doc.

**Comment by aphyr** [comment]
On 11/08/2015 10:08 AM, Alexander Naumenko wrote:
>
> Thanks Kyle, that makes sense!
>
> So that's definitely not a bug or malfunction of Riemann. I didn't see 
> internals of the function (my bad, should have check it first before 
> opening new issue). It's just a bad use of that function by me. It 
> might be worth to add a warning note to the documentation. I assume 
> that could be a common use case (recent 24hour aggregation). And that 
> function makes a good candidate for solving it for newbie with Riemann.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/aphyr/riemann/issues/622#issuecomment-154854661>.
>

Yeah, I don't see this so much as a bug as... the function does exactly 
what you asked for, and what you asked for is really expensive. There 
actually *isn't* a way to give you a moving window over 24 hours without 
actually storing O(24 hours) worth of events. I can suggest 
lower-fidelity approximations, but they're not semantically equivalent. :-)

--Kyle

**Comment by alecnmk** [comment]
@aphyr you're right.. so I'm going to try influxdb continuous query to calculate that number from my stored stats.
