### ISSUE TITLE
Influxdb client fails to write when persicion and time to don't match

### ISSUE THREAD

**Issue by royalaid** [riemann/riemann#624]
When using the Influxdb client built into Riemann it assume a precision of seconds. Currently I am receiving data from graylog with a precision of of MS, additionally there is no way to pass in the precision to the client. A simple work around is to divide the time by 1000 convert to int and re-associate the keyword in an smap but that is kind of hacky.

**Comment by pyr** [comment]
Hi @royalaid,

You can use `scale` (http://riemann.io/api/riemann.streams.html#var-scale) to achieve this:

```clojure
(where (tagged "influxdb") (scale 1/1000 ...))
```
