### ISSUE TITLE
Should uberjar get uploaded to clojars?

### ISSUE THREAD

**Issue by blalor** [riemann/riemann#646]
While trying to diagnose a problem with another library I want to use in my Riemann project, I realized that the riemann jar downloaded from clojars appears to be the "uberjar", and contains all of Riemann's dependencies, in addition to the Riemann classes.  This seems to foil any kind of dependency management that I'd expect from leiningen.  

Specifically, I'm trying to access `clj-tuple/tuple` from clj-tuple version 0.2.2.  I have the following `project.clj`:

```clojure
(defproject foo "0.0.1-SNAPSHOT"
    :dependencies [
        [org.clojure/clojure "1.6.0"]
        [clj-tuple           "0.2.2"]
        [riemann             "0.2.10" :exclusions [clj-tuple]]
    ]
    :profiles {
        :dev {
            :jvm-opts ["-verbose:class"]
        }
    }
)
```

When I attempt to evaluate `(require '[clj-tuple :refer [tuple]])`, I get an exception:

```
user=> (require '[clj-tuple :refer [tuple]])
[Loaded user$eval372 from __JVM_DefineClass__]
[Loaded clj_tuple__init from file:~/.m2/repository/riemann/riemann/0.2.10/riemann-0.2.10.jar]
[Loaded clj_tuple$loading__4958__auto__ from file:~/.m2/repository/riemann/riemann/0.2.10/riemann-0.2.10.jar]
[Loaded clojure.lang.PersistentUnrolledVector from file:~/.m2/repository/clj-tuple/clj-tuple/0.2.2/clj-tuple-0.2.2.jar]
[Loaded clojure.lang.PersistentUnrolledVector$Card0 from file:~/.m2/repository/clj-tuple/clj-tuple/0.2.2/clj-tuple-0.2.2.jar]
[Loaded clojure.lang.PersistentUnrolledMap from file:~/.m2/repository/clj-tuple/clj-tuple/0.2.2/clj-tuple-0.2.2.jar]
[Loaded clojure.lang.PersistentUnrolledMap$Card0 from file:~/.m2/repository/clj-tuple/clj-tuple/0.2.2/clj-tuple-0.2.2.jar]
[Loaded clj_tuple$fn__8609 from file:~/.m2/repository/riemann/riemann/0.2.10/riemann-0.2.10.jar]
[Loaded clj_tuple$hash_map from file:~/.m2/repository/riemann/riemann/0.2.10/riemann-0.2.10.jar]
[Loaded clj_tuple$vector from file:~/.m2/repository/riemann/riemann/0.2.10/riemann-0.2.10.jar]
[Loaded clojure.core$ns_interns$fn__4535 from file:~/.m2/repository/org/clojure/clojure/1.6.0/clojure-1.6.0.jar]

IllegalAccessError tuple does not exist  clojure.core/refer (core.clj:3919)
```

My theory is that only the `riemann` namespace (and its children) should be in the jar that gets uploaded to clojars, and that a separate jar should be distributed separately for those using the official download.

**Comment by pyr** [comment]
Hi @blalor,

When a leiningen project declares the `:main` key in its config, dependencies get pulled. Down the road we will split riemann into a library and dependencies, however that's not on the immediate horizon.
