### ISSUE TITLE
:webhook_uri needs more documentation in slack alerter

### ISSUE THREAD

**Issue by youngderekm** [riemann/riemann#651]
The example in the slack alerter uses account name and token for credentials.  When used in this form the code generates a URL using <account>.slack.com and the token as a query param.  I believe this form of URL is no longer supported by slack.  Passing the webhook URL directly does work, but this parameter is not described very well in the documentation.  Maybe an additional example could be added that uses `:webhook_uri`, or if slack no longer support the old form, support for it could be removed.

old form generated when using `:account` and `:token`:
`https://ACCOUNT.slack.com/services/hooks/incoming-webhook?token=TOKEN`

new form or incoming webhook that can be passed with webhook_uri:
`https://hooks.slack.com/services/XXXXX/YYYY/ZZZZZ`

**Comment by jamtur01** [comment]
@youngderekm Which example are you looking at? The HOWTO and the slack.clj both seem to have updated URL version.

**Comment by youngderekm** [comment]
I was looking here: http://riemann.io/api/riemann.slack.html

The example:
```clojure
(def credentials {:account "some_org", :token "53CR3T"})
(def slacker (slack credentials {:username "Riemann bot"
                                 :channel "#monitoring"
                                 :icon ":smile:"}))
```

The howto is a similar example.

I believe you need this form to get it to work:

```clojure
(def credentials {:webhook_uri "https://hooks.slack.com/services/XXXXX/YYYY/ZZZZZ"})
(def slacker (slack credentials {:username "Riemann bot"
                                 :channel "#ops"
                                 :icon ":smile:"}))
```

If instead I take ZZZZZ as the `:token` and the account name as `:account` I get an error response from slack status 404, "No hooks".

**Comment by jamtur01** [comment]
That example works for me. I don't get a 404.

**Comment by youngderekm** [comment]
I see my issue now.  I had an extra character in the token, which is why I got the 404.  I do think using webhook_uri is simpler and matches their current documentation at https://api.slack.com/incoming-webhooks but I agree both forms work.

**Comment by pyr** [comment]
@youngderekm thanks for confirming!
