### ISSUE TITLE
Too many email recipients error in Riemann email alert

### ISSUE THREAD

**Issue by Rajeshkumar123** [riemann/riemann#657]
I am using Riemann in my system to trigger an email alert. I have given more thann 10 email recipient address in the configuration. I am getting `Too many email recipients failed to send an email` error. When I am using 3-4 email recipient it working fine.

Is there any limitation for adding the recipient if so is there any way to overcome this issue?. I have searched many blogs and sites but I couldn't find any information regarding this.

Thanks in advance

**Comment by pyr** [comment]
I think this might be related to your MTA, rather than riemann itself.
