### ISSUE TITLE
Pagerduty with proxy settings.

### ISSUE THREAD

**Issue by liuweichu** [riemann/riemann#664]
Hi there:

This is a feature request:

We are using pagerduty's service and want Riemann to send alerts to pagerduty.com.
However, our Riemann is in our data center, and it cannot reach the internet for security reason.

As I checked pagerduty's code, it's a plain http/post request to the pagerduty API endpoint.
So it will be nice to have the proxy configuration exposed to riemann.config.

If it's ok, I can make the PR.

Regards,
Liu

**Comment by mfournier** [comment]
A lot of riemann's modules use clj-http.client, pagerduty included. So my advice would be to define the proxy config via the `EXTRA_JAVA_OPTS` envvar that riemann's startup script uses, as described here: https://github.com/dakrone/clj-http#proxies

**Comment by liuweichu** [comment]
Ok, thanks for the tips.
I guess that's the best practice for Riemann in DC.

**Comment by weichuliu** [comment]
@mfournier 
Hello, regarding to proxy, we are behind a proxy that requires proxy authorization.
If I set all `:proxy-host` `:proxy-port` `:proxy-user` `:proxy-pass` to clj-http.client, I can reach pagerduty API.
However I could not find a way to get through proxy with only setting Java network properties.
Some people on stackoverflow suggest to set `-Dhttp(s).proxyUser`, `-Dhttp(s).proxyPassword`. However, seems like jvm doesn't really respect these two. Also there is not official document describing these two properties.

It will be very helpful if you could give me some advices about this.

Regards,
Liu
