### ISSUE TITLE
async-queue! (threadpool-service) never go above core-pool-size

### ISSUE THREAD

**Issue by mreinhardt** [riemann/riemann#668]
`async-queue!` never has more than `core-pool-size` threads active or alive regardless of what `max-pool-size` is set to.

For example, with this config:

```
(let [check-threshes (async-queue!
                       :check-threshes
                       {:queue-size 3000
                        :core-pool-size 16
                        :max-pool-size 256
                       (fn [es] (stuff)))]
  (streams (batch 10000 1.0 check-threshes)))
```

Here is a sample of the relevant instrumentation metrics:

```
host        service                                         metric  state  time
my-box.abc  riemann executor check-threshes accepted rate    14.93  ok     1 min ago
my-box.abc  riemann executor check-threshes completed rate   14.39  ok     8 sec ago
my-box.abc  riemann executor check-threshes queue capacity  3000.0  ok     1 min ago
my-box.abc  riemann executor check-threshes queue size       971.0  ok     1 min ago
my-box.abc  riemann executor check-threshes queue used        0.35  ok     8 sec ago
my-box.abc  riemann executor check-threshes rejected rate      0.0  ok     1 min ago
my-box.abc  riemann executor check-threshes threads active    16.0  ok     1 min ago
my-box.abc  riemann executor check-threshes threads alive     16.0  ok     8 sec ago
```

Note that even though there's a decent sized queue to process the active and alive threads have not risen above the `core-pool-size`. My understanding is that it should grow to the `max-pool-size` when needed. Is my understanding incorrect or is this a legitimate issue?

**Comment by liuweichu** [comment]
From: http://riemann.io/howto.html#asynchronous-streams

```
```

**Comment by mreinhardt** [comment]
Further notes after dealing with this for a while...

What seems to happen is that only when a queue *hits* the max queue size do the number of executor threads increase. The problem we're having is that by that time there's no salvaging the situation. Not sure if spinning up more threads sooner or not would help or at least give us more time to address the issue, but I would be interested in considering this. For the time being we've solved this issue in separating ingest and processing by forwarding a subset of events to another server.

**Comment by pyr** [comment]
Yes, this is the current behavior, another one would be to have a threshold at which to start growing the pool.
