### ISSUE TITLE
graphite pickle/batched writes

### ISSUE THREAD

**Issue by leifwalsh** [riemann/riemann#671]
The [graphite protocol](http://graphite.readthedocs.org/en/latest/feeding-carbon.html) supports a text-based protocol and a pickle-based protocol.  The pickle protocol supports batching.

I propose we add to the graphite event sink the ability to send events pickled, and support batched writes.  Pyrolite provides a [pickle module](https://github.com/irmen/Pyrolite/blob/master/java/src/main/java/net/razorvine/pickle/Pickler.java#L100) which we could use to serialize events.

**Comment by jamtur01** [comment]
+1 - would welcome this patch.

**Comment by pyr** [comment]
Thanks for the suggestion @leifwalsh will close for now and re-open if a PR  comes along implementing this.
