### ISSUE TITLE
Using project to combine events generates unexpected event and metric

### ISSUE THREAD

**Issue by abailly** [riemann/riemann#675]
I am trying to use [project](http://riemann.io/api/riemann.streams.html#var-project) to combine two different events in order to produce a percentage disk usage and trigger some alert when reaching some threshold:

```
   ;; handles notification for disk space
   (project [(service "df-root/df_complex-used")
             (service "df-root/df_complex-free")]
            (smap (partial folds/fold
                           (fn [u f]
                             (do (print "ratio " u f )
                                 (/ u (+ u f)))))
                  (with :service "df-root/percent-used"
                        (split
                         (< 0.9  metric) (with :state "critical"
                                               slacker-critical
                                               index)
                         (< 0.75 metric) (with :state "warning"
                                               slacker-warning
                                               index)
                         (with :state "ok" index)))))
```
The problem is that I sometimes get events like:

```
Critical: df-root/percent-used on lending-2016-01-28 reached 4.7179616256E10
[19:47] 
Critical: df-root/percent-used on lending-2016-01-28 reached 1.285986304E10
```

which does not make much sense too me. I tried writing some tests for this function:

```
(tests
 (deftest ratio-test
   (is (= (inject! [{:service "df-root/df_complex-used"
                     :metric 12
                     :time    1}
                    {:service "df-root/df_complex-free"
                     :metric 24
                     :time    1}])
          {:index [{:service "df-root/percent-used"
                    :metric  (/ 1 3)
                    :state   "ok"}]}))))
```
which fails with following errors:

```
FAIL in (ratio-test) (riemann.config:127)
expected: (= (inject! [{:service "df-root/df_complex-used", :metric 12, :time 1} {:service "df-root/df_complex-free", :metric 24, :time 1}]) {:index [{:service "df-root/percent-used", :metric (/ 1 3), :state "ok"}]})
  actual: (not (= {:index [{:ttl 60, :state "critical", :service "df-root/percent-used", :time 1, :metric 12} {:ttl 60, :service "df-root/df_complex-used", :time 1, :metric 12} {:ttl 60, :state "ok", :service "df-root/percent-used", :time 1, :metric 1/3} {:ttl 60, :service "df-root/df_complex-free", :time 1, :metric 24}]} {:index [{:service "df-root/percent-used", :metric 1/3, :state "ok"}]}))
```

What am I doing wrong?

**Comment by abailly** [comment]
For a single host, this generates a flaky event, with `percent-used` value flipping between 0.9 and 0.6. Those two screenshots were taken at 5s interval on a riemann dashboard:

![screen shot 2016-04-06 at 21 44 09](https://cloud.githubusercontent.com/assets/40221/14330455/e8349f4c-fc40-11e5-87a7-ae532bbfc410.png)
![screen shot 2016-04-06 at 21 44 14](https://cloud.githubusercontent.com/assets/40221/14330456/e8352db8-fc40-11e5-8862-4e6852e8373f.png)

**Comment by liuweichu** [comment]
In my understanding (correct my if I'm wrong), `project` doesn't promise you get the data with the same timestamp or same host. It is called on updating of either "df-root/df_complex-used" or "df-root/df_complex-free" event reaches.

However it is weird to get  (/ u (+ u f)) larger than 1. You'd better try to print out (use `info`) the two events to see what happened here.

By the way, not directly related to riemann, but if you just want to get df percent, you can update collectd to 5.5.0. It provides percentage data for df, cpu, mem, etc.

**Comment by faxm0dem** [comment]
As a workaround, could you try using `folds/quotient-sloppy` instead?

**Comment by abailly** [comment]
OK, that makes sense. And in this case, if *one* of the event arrives without the other, then percent computation will go afoul and yield stupid numbers, right?

**Comment by abailly** [comment]
@faxm0dem This returns the quotient of the two numbers but I need to sum them up before that. However I will have a look at source code, might give hints on how to implement properly what I want.

**Comment by abailly** [comment]
@liuweichu Yeah, I know I should upgrade to collectd also for reasons related to proper behaviour as a client

**Comment by jamtur01** [comment]
@abailly Do you need anymore help here?

**Comment by pyr** [comment]
@abailly as mentioned, this is the expected behavior of project, guarding against nil value is up to the consumer code.

**Comment by abailly** [comment]
Apologies for not having answered earlier. I will take care of checking null values. Thanks

**Comment by pyr** [comment]
@abailly no problem :-)
