### ISSUE TITLE
Events not being reinjected to the main streams after TTL is expired.

### ISSUE THREAD

**Issue by pkaleta** [riemann/riemann#676]
I’m having the following problem with riemann: Depending on the value of TTL, events are reinjected or not to the main streams with the expired state. More specifically, if the TTL is lower, e.g. 60 seconds, everything works as expected — when TTL is down to 0, the event is successfully reinjected and appears in my `expired` event handlers. If I increase the TTL to 90, the event never appears in the stream filters again. I can see it present in index (using riemann-dash) and disappear from there after 90 seconds.

Here's a shortened example of the code I'm running:

```clojure
; config.clj
(logging/init {:console true})
(tcp-server {})
(ws-server {})
(instrumentation {:enabled? false})


(periodically-expire 5)


(let [index (index)]
  (streams
   (sdo
    index
    (where (and (service "celery task success count"))
           (with {:service "celery_heartbeat"
                  :ttl 90  ; changing this value to 60 makes the event appear in the logs
                  :metric 1
                  :description "Latest sent celery success event"}
                 index))
    (where (service "celery_heartbeat") #(info "received event" %)))))

```

I can see the `celery_heartbeat` events appear in riemann dash. Then I stop the celery and wait. When TTL is 60 seconds, the `info` function gets executed and I see the event in the logs. When it's 90, it never appears.

I'm using Ubuntu 14.04.1 LTS and riemann 0.2.10.

**Comment by pkaleta** [comment]
I made sure that it's not the `email` that is being throttled or sth. Tried with `info` and no relevant log lines appear with TTL of 90 whereas they do if TTL is 60.

**Comment by pkaleta** [comment]
I was able to fix the above code to work properly. Yet I still do not completely understand if my understanding of what happens is correct.

The sequence of events I'm executing is:

1. Start riemann using `riemann config.clj`.
2. Connect to riemann using `riemann-dash`.
3. Send the `{:service "celery task success count"}` to riemann using [bernhard riemann python client](celery task success count):

 ```python
import bernhard
c = bernhard.Client()
c.send({'host': 'awesome.host.com', 'service': 'celery task success count'})
```

 This causes the `{:service "celery_heartbeat"}` to be injected into the index.

 I've got this in riemann-dash after this step, which is expected:

 <img width="1037" alt="screen shot 2016-04-08 at 1 23 21 pm" src="https://cloud.githubusercontent.com/assets/51424/14373495/15b1cffa-fd8e-11e5-9fa6-17e7d76a3972.png">

4. Wait 60 seconds until the initial `{:service "celery task success count"}` event expires. Once it does, I've got this:

 <img width="1037" alt="screen shot 2016-04-08 at 1 23 38 pm" src="https://cloud.githubusercontent.com/assets/51424/14373510/425b93ec-fd8e-11e5-94e2-6d4b121de9da.png">

 Because of the fact that `(where (and (service "celery task success count"))` line doesn't filter out the expired events, another `{:service "celery_heartbeat"}` event is injected into the index, this time with the `:state "expired"`, I assume.

5. Now I wait another ~30 seconds for the first `{:service "celery_heartbeat"}` event to be expired. This happens, according to riemann-dash:

<img width="1039" alt="screen shot 2016-04-08 at 1 24 05 pm" src="https://cloud.githubusercontent.com/assets/51424/14373568/ba29173c-fd8e-11e5-91c8-7772b6f9b88c.png">

 but no `"celery_heartbeat"` events are re-injected into the `streams` with state "expired". Is this because of the fact that the event has its state already changed to "expired" in the index before due to `with`? If so, it wasn't entirely clear from the documentation.

I'm leaving this here in case someone has a similar problem in future.

The solution I've implemented was to simply change the `where` filter, so that it only passes non-expired events.

**Comment by jamtur01** [comment]
Okay - I'm going to close this for now.

**Comment by jamtur01** [comment]
Okay - I'm going to close this for now.

**Comment by jamtur01** [comment]
Okay - I'm going to close this for now.

**Comment by jamtur01** [comment]
Okay - I'm going to close this for now.

**Comment by jamtur01** [comment]
Okay - I'm going to close this for now.

**Comment by jamtur01** [comment]
Okay - I'm going to close this for now.

**Comment by jamtur01** [comment]
Okay - I'm going to close this for now.

**Comment by jamtur01** [comment]
Okay - I'm going to close this for now.

**Comment by jamtur01** [comment]
Okay - I'm going to close this for now.

**Comment by jamtur01** [comment]
Okay - I'm going to close this for now.

**Comment by faxm0dem** [comment]
Sheldon!

**Comment by jamtur01** [comment]
@faxm0dem I don't know what that means?

**Comment by faxm0dem** [comment]
github bug: saw your comment 16 times. was referring to the big bang theory TV show

**Comment by jamtur01** [comment]
@faxm0dem Ah have not seen it. Weird! :)

**Comment by pyr** [comment]
Saw it too. Likely a transient GH glitch

On May 3, 2016 5:47:17 PM CEST, Fabien Wernli <notifications@github.com> wrote:
>github bug: saw your comment 16 times. was referring to the big bang
>theory TV show
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/riemann/riemann/issues/676#issuecomment-216572354

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gsriram7** [comment]
I have the same problem as described by @pkaleta. I ve a similar config to receive heartbeats from samza stream tasks and to send a slack alert when the event expires. I can see the event expiring in riemann-dash but it isn't reinjected to the stream. Because of that I am unable to get service down alerts. Is there any explanation on why is it happening? Is the issue fixed?

**Comment by pkaleta** [comment]
@gsriram7 have you seen this comment: https://github.com/riemann/riemann/issues/676#issuecomment-207196958
