### ISSUE TITLE
Client might be not reading acks fast enough or network is broken

### ISSUE THREAD

**Issue by faxm0dem** [riemann/riemann#686]
This is the error message I'm getting since `0.2.11` when issuing a query to the tcp-server having a reasonable-ish number of results (112). When removing the `(channelWritabilityChanged)` block from the code, everything runs smooth, I'm even able to query `true` which on my test server returns 18574 results.

Tested with `riemann-c-client` and `perl(Riemann::Client)`.

As discussed on IRC @abailly consider yourself poked

**Comment by abailly** [comment]
I do :-)

**Comment by faxm0dem** [comment]
just for the record

```
☠ time riemann-client query 'true' | grep -c Event
18574

real    0m0.963s
user    0m0.341s
sys     0m0.132s
☠ riemann-client query 'service =~ "%index size%"'
Event #0:
  time  = 1462957956 - Wed May 11 11:12:36 2016
  state = ok
  service = riemann index size
  host = ccosvms0046
  description = (null)
  ttl = 20.000000
  metric_sint64 = 18574
  metric_f = 18574.000000
```

**Comment by abailly** [comment]
Quick question: does it also fails when using localhost interface? Just
asking because it would help in writing test case...

**Comment by faxm0dem** [comment]
yeah, I still get the message

**Comment by abailly** [comment]
Cool. Thanks and apologies for the gross simplification in client
handling....

**Comment by faxm0dem** [comment]
please don't apologize for contributing!
