### ISSUE TITLE
Its not an issue but a question

### ISSUE THREAD

**Issue by sujithnss** [riemann/riemann#687]
Hi All

I'm pretty new to Riemann. I would like to know how we can configure and install Riemann not via RPM install but just cloning this repository and building the same or via tar gz files. I have a CentOs7 installed in Virtual Box.

Sorry for asking this basic question here as I didnt find any alternate option to ask a query :-)

Best Regards
Sujith P V

**Comment by jamtur01** [comment]
Please see - http://riemann.io/howto.html#work-with-the-riemann-source

**Comment by sujithnss** [comment]
Thanks James...I had tried the tar gz file approach and extracted the same. But post that I was clueless on how to proceed further. I was confused on how to run the same in this scenario. Because "service riemann start" does not helped me. Could you please advise.

**Comment by jamtur01** [comment]
Why not use the packages? They have service management - the raw jar does not.

If you wish to use the jar file.

1. Create the jar file with `lein uberjar`?

2. Run the jar file with the `java` binary.

```sh
java -jar riemann.jar -config /etc/riemann/riemann.config
```

**Comment by sujithnss** [comment]
Thanks James.
