### ISSUE TITLE
Query : Riemann Slack integration

### ISSUE THREAD

**Issue by sujithnss** [riemann/riemann#688]
Hi

I was trying to integrate Riemann to Slack and I was following the code snippet given in the How to section and added the same in reimann.config. Here I was getting an error like "Unable to resolve symbol : slack in this context, compiling (/etc/riemann/riemann.config)"

Any help will be much appreciated.

Thanks in advance
Sujith PV

**Comment by jamtur01** [comment]
This was resolved on the mailing list.
