### ISSUE TITLE
Question : lein run on the cloned Riemann git 

### ISSUE THREAD

**Issue by sujithnss** [riemann/riemann#698]
Hi

I just cloned the current repo and tried to build it via Leiningen and recieved the below error (I tried this in a new machine which does not have any Riemann instance running)

**ERROR [2016-05-31 07:38:18,219] main - riemann.bin - Couldn't start
java.util.concurrent.ExecutionException: io.netty.channel.unix.Errors$NativeIoException: bind() failed: Address already in use
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)**

Any help would be great.

Best Regards
Sujith P V

**Comment by jamtur01** [comment]
You have something bound to the same address and port as Riemann. Another instance running perhaps.

**Comment by jamtur01** [comment]
Also please use the mailing list for technical questions like this. We'd prefer to keep GH issues for bugs and features. Thanks!

**Comment by sujithnss** [comment]
Thanks James. Could you please ping me the mailing list

**Comment by jamtur01** [comment]
http://riemann.io/support.html
