### ISSUE TITLE
REST interface for integrating with local services

### ISSUE THREAD

**Issue by raj2569** [riemann/riemann#703]
Hi,

We have a requirement to send the alerts as SMS to our support staff. We already have a small REST based interface for sending SMS and looking to integrate alerts from riemann in to it. Unfortunately riemann does not support sending alerts to a local REST based service. 

pagerduty plugin has all the alerting that we need, we just need to provide our URL instead of pagerduty. We can then write a REST server to translate it in our SMS gateway. 

So is it possible to change the pagerduty plugin to take the REST URL as parameter? If no URL is provided let the pagerduty as default.

Thanks!

**Comment by jamtur01** [comment]
I don't think exposing the URL is useful to many folks beyond this niche. But since you only want to change that line - you could easily write your own variant of the pagerduty plugin though and include it (http://riemann.io/howto.html#including-functions-from-multiple-sources).
