### ISSUE TITLE
Include distribution files in GitHub releases?

### ISSUE THREAD

**Issue by apjanke** [riemann/riemann#716]
Hi Riemann folks,

Would you consider publishing the distribution files to the tagged GitHub releases, along with the source tree snapshots that GitHub auto-creates? It looks like the main download site links like https://aphyr.com/riemann/riemann-0.2.11.tar.bz2 are rate-limited – we've been [getting errors when doing multiple downloads of the files](https://github.com/Homebrew/homebrew-core/pull/1246). The GitHub releases pages aren't limited like that, so it would be a convenience for Homebrew and other Riemann users to have the alternate download links available.

Cheers,
Andrew

**Comment by dch** [comment]
On Mon, 22 Aug 2016, at 18:56, Andrew Janke wrote:
> Hi Riemann folks,
>
> Would you consider publishing the distribution files to the
> tagged GitHub
> releases, along with the source tree snapshots that GitHub auto-
> creates?
> It looks like the main download site links like
> https://aphyr.com/riemann/riemann-0.2.11.tar.bz2 are rate-
> limited – we've
> been [getting errors when doing multiple downloads of the
> files](https://github.com/Homebrew/homebrew-core/pull/1246).
> The GitHub
> releases pages aren't limited like that, so it would be a
> convenience for
> Homebrew and other Riemann users to have the alternate download links
> available.
>
> Cheers,
> Andrew

I already host these at
https://wintermute.skunkwerks.at/riemann/releases/
as I have the same constraints as part of the FreeBSD port I maintain:
https://www.freshports.org/net-mgmt/riemann

IIRC Kyle has a login for adding releases and I'm happy hooking into
future build process improvements.

BTW I'm pretty sure you'll run out of bandwidth before I do :-)

Dave
—
  Dave Cottlehuber
  +43 67 67 22 44 78
  Managing Director
  Skunkwerks, GmbH
  http://skunkwerks.at/

**Comment by apjanke** [comment]
Thanks @dch! Going to use your site as a mirror.

**Comment by jamtur01** [comment]
@pyr We should probably publish to GH and @aphyr's site.

**Comment by pyr** [comment]
I agree about pushing to GH releases.

**Comment by aphyr** [comment]
Yeah now that GH releases exists, no need to publish to my site. :-)
On Sep 6, 2016 1:51 AM, Pierre-Yves Ritschard <notifications@github.com> wrote:I agree about pushing to GH releases.

**Comment by jamtur01** [comment]
In the short term I've added the packages to a release here:

https://github.com/riemann/riemann/releases/tag/0.2.11

**Comment by jamtur01** [comment]
Done.
