### ISSUE TITLE
Hosting of RPMs & DEBs

### ISSUE THREAD

**Issue by pradeepchhetri** [riemann/riemann#718]
Currently RPMs & DEBs are being hosted at https://aphyr.com

I have some experience in hosting YUM & DEB repositories via packagecloud (https://packagecloud.io). I think they are free for open-source projects.

I would like to know if you see any value in migrating to packagecloud. 

Thanks !!

**Comment by jamtur01** [comment]
In the short term I've added the packages to a release here:

https://github.com/riemann/riemann/releases/tag/0.2.11

**Comment by jamtur01** [comment]
I think we might start with GH. Closing as duplicate of #716
