### ISSUE TITLE
ws-server binds to all interfaces/IP addresses even if config requires otherwise

### ISSUE THREAD

**Issue by dch** [riemann/riemann#721]
This seems to be present in master, even though we switched `aleph` for `httpkit`. The original message is here https://github.com/riemann/riemann/issues/156 but if there is no fix possible it might make more sense to have `ws-server` throw an error if a `:host ...` is passed in as config.

**Comment by faxm0dem** [comment]
I can confirm this. The value of  `:host` is completely ignored

**Comment by mcorbin** [comment]
I found why :host is ignored.http-kit need the :ip option and not :host [here](https://github.com/riemann/riemann/blob/master/src/riemann/transport/websockets.clj#L186).
I made a PR.
