### ISSUE TITLE
Document supported influxdb versions

### ISSUE THREAD

**Issue by jmcarp** [riemann/riemann#723]
The inline documentation at https://github.com/riemann/riemann/blob/0.2.11/src/riemann/influxdb.clj#L2 indicates that only influxdb 0.8.x and 0.9.x are supported, but influxdb versions up to at least 0.13 appear to work. The docs should be updated to clarify which versions of influxdb are supported.

Related: is version 1.0.0 currently supported? I haven't tried it out yet.

**Comment by jamtur01** [comment]
@jmcarp If you can confirm that you've tested those versions (influxdb support has been varied and flakey) then we'd welcome a patch updating the documentation. Thanks!

**Comment by erSitzt** [comment]
I'm using riemann with influxdb 0.9 and 1.0  (both with the same config in riemann)

`
(def send-to-influxdb
  (adjust #(assoc % :time (* 1/1000 (:time %)))
    (influxdb {:host "172.26.1.101" :port 8086 :username "user" :password "pass" :db "metrics" :scheme "http" :version :0.9})
  ))
`

**Comment by mcorbin** [comment]
Riemann should support influx 0.9 and higher.
