### ISSUE TITLE
netty 64bit shared library fails on non-glibc systems

### ISSUE THREAD

**Issue by oholiab** [riemann/riemann#725]
I have no idea how to fix this so I can't guarantee that it's going to make it work on the platform but I'd guess that the solution used for #508 should probably work to at least eliminate this bug...

Effectively I tried running riemann in an alpine linux docker container and got:

```
java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: /tmp/libnetty-transport-native-epoll4689781591683070059.so: Error relocating /tmp/libnetty-transport-native-epoll4689781591683070059.so: __strndup: symbol not found
```

I found #505 and #508 after googling the error, and I would imagine that using the pure-Java epoll used as a getaround for non-linux64 would circumvent this for musl-based distributions.

**Comment by martinssipenko** [comment]
Having the same issue, when trying to run riemann on Alpine linux in docker.

**Comment by mcorbin** [comment]
-Dnetty.epoll.enabled=false should fix this.

**Comment by martinssipenko** [comment]
thanks!
