### ISSUE TITLE
Suppress exception logging if the exception is handled by `exception-stream`

### ISSUE THREAD

**Issue by liuweichu** [riemann/riemann#726]
Hi there,

I'm using `exception-stream` with `async-queue!` to forward events to influxdb:

```clojure
(exception-stream
  #(warn "Failed to forward" (count (:event %)) "events") ; Brief report if failed
  (async-queue! :influxdb-queue async-queue-opts
    (influxdb influxdb-opts)))
```

It works (almost) perfectly that if posting to influxdb fails, I get a brief report.

However, the original exception is still logged (62 lines! of meaningless stack), which is kind of annoying.

Is there a way to suppress the original warning? (Which I think should be the default behavior though)

**Comment by faxm0dem** [comment]
I've wanted to do this for a long time but been to lazy to dig into the code :-/
