### ISSUE TITLE
riemann executor rejected rate is always 0

### ISSUE THREAD

**Issue by faxm0dem** [riemann/riemann#727]
Even if the queue is full (as seen from instrumentation)  and riemann drops events (as seen from the logfile) it seems the `rejected rate` is always zero.
After looking at [the source code](https://github.com/riemann/riemann/blob/master/src/riemann/service.clj#L207) it becomes clear why (EDIT: unless I misunderstand something).

Has this been done because the `ThreadPoolExecutor` java class does not give this information?
If that's the case, I'd rather have a `NaN` instead of false information :-)

**Comment by faxm0dem** [comment]
I now understand from [these lines](https://github.com/riemann/riemann/blob/master/src/riemann/service.clj#L176-L177) that the logic to increment the rejected stats is present in the code.

However, the rejected rate is always 0 nevertheless.

Can anybody confirm that?

**Comment by mcorbin** [comment]
Do you have a riemann.config file or something for generating dropped events ? I can work on this issue but i don't know how to create dropped events.

**Comment by aszecowka** [comment]
@faxm0dem @mcorbin Have you found out why rejected rate is always hardcoded to 0?

**Comment by mcorbin** [comment]
@aszecowka I haven't reproduce the issue yet.

@faxm0dem can you provide a test case ?

**Comment by faxm0dem** [comment]
I'll close this for now. I'll reopen when ready
