### ISSUE TITLE
[Feature request] Influxdb supports dynamic database & retention policy targeting

### ISSUE THREAD

**Issue by liuweichu** [riemann/riemann#730]
When creating an `influxdb` function, nice to have the option to pass functions that determine which database and which retention policy an event should go to.
# Example

``` clojure
; riemann.config

(defn get-db-name "User defined fn to get db" [event] (:db event))
(defn get-rp-name "User defined fn to get rp" [event] (:rp event))


(let [dynamic-influxdb-forwarding
      (influxdb {:host "influxdb.example.com"
                 :db "my_db"
                 :db-fn get-db-name ; ✨Optional, if nil, fallback to :db
                 :rp-fn get-rp-name ; ✨Optional
                 :user "riemann"
                 :password "secret"})]
  (streams dynamic-influxdb-forwarding)) 
```

So that if the following batch of events are sent to `dynamic-influxdb-forwarding`

``` clojure
'(
    {:db "db_1"            :host "..." :service "event 0" :state nil :description nil :metric 0 :tags [] :time 0 :ttl 10}
    {:db "db_1"            :host "..." :service "event 1" :state nil :description nil :metric 0 :tags [] :time 0 :ttl 10}
    {:db "db_2"            :host "..." :service "event 2" :state nil :description nil :metric 0 :tags [] :time 0 :ttl 10}
    {:db "db_2"            :host "..." :service "event 3" :state nil :description nil :metric 0 :tags [] :time 0 :ttl 10}
    {:db "db_1" :rp "rp_1" :host "..." :service "event 4" :state nil :description nil :metric 0 :tags [] :time 0 :ttl 10}
    {                      :host "..." :service "event 5" :state nil :description nil :metric 0 :tags [] :time 0 :ttl 10}
)
```

They would be sent with 4 queries:

```
influxdb.example.com:8086/write?db=db_1         (posting event 0 + event 1)
influxdb.example.com:8086/write?db=db_2         (posting event 2 + event 3)
influxdb.example.com:8086/write?db=db_1&rp=rp_1 (posting event 4)
influxdb.example.com:8086/write?db=my_db        (posting event 5)
```
# Why this, instead of simply creating multiple influxdb functions and then pipe events respectively.

Because:
1. This makes the control flow in `riemann.config` cleaner for we only need one `influxdb` function.
2. Usually as an IO function, Influxdb forwarding function is deeply wrapped under `batch` and `async-queue!`. So we have less batches and less async queues on running.
3. When we want to pipe events into new database/retention policy, no need to create new functions, no need to hardcode new database name.
# Caveat

On Influxdb side, if database doesnot exist, it will reject events

**Comment by liuweichu** [comment]
@mcorbin 
Hi,
Good to find you are doing a refactoring on `influxdb.clj`.
Can you take a look into this feature request? Either approve or reject it

**Comment by mcorbin** [comment]
Hi,
I am not a Riemann maintainer so i cannot approve or reject your PR ;)
If your PR is accepted, i can easily add your code to my refactoring ;)

On the other hand, why use a fn to determine the database and the retention and not a simple string, for example {:host "localhost" :service "test" :metric 10 :influxdb-db "mydb" :influxdb-retention "retention"} ?

**Comment by liuweichu** [comment]
> On the other hand, why use a fn to determine the database and the retention and not a simple string, for example {:host "localhost" :service "test" :metric 10 :influxdb-db "mydb" :influxdb-retention "retention"} ?

Our Riemann gets metrics from different sources, e.g. `collectd` and metrics from our cloud platform components. They are mixed and processed together inside Riemann. Plus Riemann Instrumentation, we have metrics from 3 sources.

We wanted to forward metrics respectively to 3 databases, however, 

```
```



In that case, you will need to create a new `influxdb` function for each `db/rp` pairs, which means many more `async-queue!`, and more complicated control flow in `riemann.config`.

**Comment by mcorbin** [comment]
I understand this, but if influxdb accepts string values (like in my example) for the db and the retention, you can use something like smap to add the correct values to the keys before sending the events to influx :

``clojure
(smap
   (fn [event] (assoc event :db (db-fn event))
    (influxdb opts))
```

At the end the result is the same.

**Comment by liuweichu** [comment]
@mcorbin Sounds good! As long as `influxdb` function can correctly handle batched events.

Although IMHO this kinda created some implicit dependency (e.g. the `:db` field should not be used by user otherwise they will be sent to undesired destination), and require more codes in main config. (Just nitpicking :) )

**Comment by mcorbin** [comment]
My PR (#741) fix it.

**Comment by liuweichu** [comment]
Great! @mcorbin 👍 
Looking forward to the new version to be released
