### ISSUE TITLE
release: prometheus

### ISSUE THREAD

**Issue by donovan-graham** [riemann/riemann#733]
Hi I'm wondering if a new release is scheduled, which might make `prometheus` available

**Comment by anho** [comment]
@aphyr @pyr @jamtur01 anyone of you able to given an ETA?

**Comment by mcorbin** [comment]
+1.
Also, it would be nice to merge opened PRs.

**Comment by shinji62** [comment]
+1 Any chance to build a new version ? @aphyr @pyr @jamtur01

**Comment by faxm0dem** [comment]
They are all quite busy currently. Can we assist you with building a jar or rpm in the meantime?

**Comment by shinji62** [comment]
I built it. But releasing it could be beneficial.

**Comment by faxm0dem** [comment]
okidoki, I agree, as there are some outstanding bugs which aren't even merged yet like #737 and #724

**Comment by jamtur01** [comment]
Released.
