### ISSUE TITLE
[Feature request] support microseconds in :time

### ISSUE THREAD

**Issue by mcorbin** [riemann/riemann#738]
On @aphyr suggestion, i started working on milliseconds support in the Riemann protocol.Here is my approach :

In riemann-java-client i  added an **optional int64 time_micros** field in proto.proto.

In riemann-clojure-client/codec.clj, i did :

``` clojure

(defn decode-pb-event-record
  "Transforms a java protobuf to an Event."
  [^Proto$Event e]
  (Event.
    (when (.hasHost e)        (.getHost e))
    (when (.hasService e)     (.getService e))
    (when (.hasState e)       (.getState e))
    (when (.hasDescription e) (.getDescription e))
    (cond
      (.hasMetricSint64 e)    (.getMetricSint64 e)
      (.hasMetricD e)         (.getMetricD e)
      (.hasMetricF e)         (.getMetricF e))
    (when (< 0 (.getTagsCount e)) (vec (.getTagsList e)))
    (cond   (.hasTime e)       (* 1000 (.getTime e)) ;; time in s => ms
            (.hasTimeMicros e) (.getTimeMicros e) ;; time in ms
            true               (System/currentTimeMillis)) ;; default
    (when (.hasTtl e)         (.getTtl e))))

```

With this, the event :time key is always milliseconds. If a client is sending seconds, i transform the :time to milliseconds.

In Riemann, the code needs modification in many places. For example, :ttl is in seconds, so i need to multiply it by 1000 when comparing with :time (for expiration). I also need to check all tests files to see the impact (like in query_test.clj). And of course time.clj itself.

What do you think of this ? Is it the right way to do it ?

**Comment by aphyr** [comment]
`time_micros` should probably be in microseconds, not milliseconds, so you want to convert by 10^6, not 10^3, to get back to seconds. In the decoding phase... rationals would preserve precision but they're real slow, so it might make sense to go for a double. I'd leave Riemann's internal time in seconds for now; switching everything over to micros can be a separate project.

**Comment by mcorbin** [comment]
Good catch, what a dumb mistake ;) 
If i leave time in seconds in Riemann but accept microseconds in the protocol (and in the clojure client) , it will cause errors no ?

**Comment by aphyr** [comment]
Well the idea is you convert back and forth, so nobody notices. :)

**Comment by mcorbin** [comment]
OK. I will just accepts microseconds and convert it to seconds in Riemann in a first time, and switch to micros in Riemann in a second time.

**Comment by mcorbin** [comment]
A last question : is milliseconds in Riemann's internal not enough ? I don't event know how to get time in microseconds in java.

**Comment by aphyr** [comment]
No, you can't get a finer resolution clock than milliseconds in the JVM, but that's OK. Just like :metric, you'll want to fill in both `time` and `time_micros`, downsampling where necessary.

**Comment by mcorbin** [comment]
Ok. I made PR in the java client and the clojure client to add the time_micros field in the protocol. If it is ok for everyone, i will work on using microseconds by default in Riemann (but before i will try to close some issues in the java client, and do the netty 4 upgrade). 
btw, thx for your help ;)

**Comment by mcorbin** [comment]
My PR on the java and clojure client are merged. Now, we just need a release of the java and clojure client and update the version used by Riemann.

**Comment by mcorbin** [comment]
All PR are merged, tests are fixed, Riemann protocol should now fully support microseconds time resolution ;)
I close this issue. cc @pyr @jamtur01

**Comment by faxm0dem** [comment]
\o/ mcorbin++
