### ISSUE TITLE
[InfluxDB] Allow :tag-fields to be set per-event 

### ISSUE THREAD

**Issue by karbak** [riemann/riemann#742]
InfluxDB indexes tags and not fields (as documented [here](https://docs.influxdata.com/influxdb/v1.1/concepts/schema_and_data_layout/)). Therefore, for performance reasons, any query-able data/metadata in InfluxDB should be stored as key-value tags.

The only way to distinguish tags from fields in `riemann.influxdb` currently is to pass in a pre-defined set of tags in `:tag-fields`  within the `opts` map argument to the influxdb-9 (influxdb) function. This function is generally called once during setup of the batch event sender (with async-queue!). It's unclear how (or if) this can be changed so `:tag-fields` can be reset per event.

**Comment by karbak** [comment]
Discussed in the riemann-users group in this [thread](https://groups.google.com/forum/#!searchin/riemann-users/influxdb%7Csort:relevance/riemann-users/hfnhu9Um4Sk/73Nth-cgBAAJ).

**Comment by mcorbin** [comment]
My PR fix it.

**Comment by jamtur01** [comment]
Fixed.
