### ISSUE TITLE
[Feature request] keep streams state between reloads

### ISSUE THREAD

**Issue by mcorbin** [riemann/riemann#743]
Actually, streams like fixed-time-window, throttle, rollup, coalesce... lose their states between reloads. For example, throttle lose his counter and its time when reloading.
I think we can modify these streams to not lose their states. I was thinking about something to do that. For example, let's take the throttle stream :

`(throttle 1 60 #(info %))` will have the actual behavior (lose state between reloads). 
`(throttle 1 60 :my-stream-name #(info %))` will keep the stream state between reloads. The third parameter (**:my-stream-name**) is an identifier.

In src/riemann/streams.clj, i defined an atom :

```clojure
(def stream-state (atom {}))
```

This atom contains the state for each stream. 

Throttle use part-time-simple to manage its time window. If i want to keep the part-time-simple state, i need to keep the "[state](https://github.com/riemann/riemann/blob/master/src/riemann/streams.clj#L589)" atom (and maybe the "anchor" variable too).

The actual part-time-simple definition can be replaced by

```clojure
  ([dt reset add finish]
   (part-time-simple dt reset add (fn [state event]) finish nil))
  ([dt reset add side-effects finish]
   (part-time-simple dt reset add side-effects finish nil))
  ([dt reset add side-effects finish stream-name]
```

There is a new parameter (stream-name), which is in my case **:my-stream-name**
Now, at the beginning of part-time-simple, i :

- check if the stream-name (:my-stream-name) key is present in my **stream-state** atom
- If yes, i initialize the state variable with the value associated with the stream-name key, and i schedule (with once!) the next part-time-simple tick if the :scheduled key is present in the state (that means that riemann reloads before the next part-time-simple tick).
- If no, i initialize the state.
- I assoc the new state variable to stream-name key in **stream-state** (so stream-state = {:my-stream-name <state>}
- That it, the rest of the stream does not change.

I quickly tested this in a branch and it *seems* to work, state is not lost between reloads. But before going further, i need your opinion :

- Is losing the streams states between reloads is a problem for you ?
- What do you think about my way of doing it ?
- Do you have other ideas to keep streams states between reloads ?

I hope my explanations are clear ;)

**Comment by faxm0dem** [comment]
I would love that feature merged. Maybe people rely on the current behaviour - we could make the change optional

**Comment by Ben-M** [comment]
I'd like to have this! There are some use cases that our users have asked for that we've had to push back on because we are worried about losing state too frequently.

**Comment by faxm0dem** [comment]
Two thoughts popped up:

1. What happens when a named stream's parameters change? It should keep the "old" behaviour yes?
1. What happens when a stream is removed: what happens with its child streams?

**Comment by mcorbin** [comment]
@faxm0dem The current behavior does not change if you don't specify an identifier. For example, in throttle i test if the third parameter is a keyword. If yes, i use the new behavior.

1. What happens when a named stream's parameters change? It should keep the "old" behaviour yes?

=> If i do `(throttle 1 60 :my-stream-name #(info %))` and modify it to `(throttle 1 60 :my-new-stream-name #(info %))` and reload, the state is reset.

2. What happens when a stream is removed: what happens with its child streams?
=> Nothing. I just keep the state (a variable/datastructure : the counter in throttle, the ConcurrentHashMap coalesce...) between reloads, and not the childs. 

 I still have to find how to delete the unused states from my **stream-state** atom (when a stream is deleted or iits name changed, the stream state in **stream-state** need to be deleted. I can maybe use 2 variables, stream-state and new-stream-state like core and new-core in Riemann).

**Comment by faxm0dem** [comment]
I meant, what happens when modifying `(throttle 1 60 :foo)` into `(throttle 2 60 :foo)`?

My other question should have been: will weird things happen when I change to much stuff in stream tree, like events ending up in child streams where they should never have etc. ?

**Comment by mcorbin** [comment]
If you have `(throttle 1 60 :foo)`:

- You receive a message, throttle let it pass and increment its counter.
- You receive a second message, throttle block the message and increment its counter
- You reload Riemann with `(throttle 2 60 :foo)`
- You receive a message, and throttle block again the message because it has already received 2 messages before the reload. You need to wait the next tick.

I can eventually reset the stream state if some parameters (like the number of messages or seconds) changes between reloads.

- will weird things happen when I change to much stuff in stream tree, like events ending up in child streams where they should never have etc. ?

If you have `(coalesce :foo a-stream)` and reloads with `(coalesce :foo a-stream a-new stream)`, a-new-stream will receive the old coalesce state.
You can have weird things if you give 2 streams the same name or things like this.

**Comment by faxm0dem** [comment]
sounds pretty good to me :-)

**Comment by mcorbin** [comment]
I made a branch where the coalesce stream keeps its state between reloads.

I have added some variables/fn in [stream.clj](https://github.com/mcorbin/riemann/blob/coalesce-state-reload/src/riemann/streams.clj#L1167-L1188) :

You can also look how i modify the coalesce stream [here](https://github.com/mcorbin/riemann/blob/coalesce-state-reload/src/riemann/streams.clj#L1205-L1220).

In the coalesce stream, is i receive a keyword parameter (like `(coalesce :foo)` `(coalesce 1 :foo)`) i will keep the state. If the keyword parameters exists in the **stream-state** atom, i use the value as state. If not i create a new state.
I also put in the **next-stream-state** atom the new state.

When riemann reload, i will call the **stream-state-transition!** fn ([here](https://github.com/mcorbin/riemann/blob/coalesce-state-reload/src/riemann/bin.clj#L43) and [here](https://github.com/mcorbin/riemann/blob/coalesce-state-reload/src/riemann/config.clj#L294). The **stream-state** value is now the **next-stream-state** value, and **next-stream-state** is reset to `{}`. With that, we do not keep unused stream states in memory.

Before going further, i want to know if i'm going in the right direction. Did i miss something in my actual implementation ?

**Comment by mcorbin** [comment]
My solution does not work. I close the issue for now.
