### ISSUE TITLE
Stream state and (by)

### ISSUE THREAD

**Issue by mcorbin** [riemann/riemann#758]
I found a limitation with the current way to deal with stream state conservation between reloads. I had not thought about it with my first PR.

```clojure
(by [:host :service]
   (coalesce {:dt 5 :stream-name :foo}
      #(info %)))
```

All substreams created by `by` will share the same state (because the :stream-name is the same for all). It is not the expected behavior. 

I don't really know how to fix this. Any idea @pyr ?

**Comment by mcorbin** [comment]
A bit hackish, maybe we can authorize :stream-name to be a vector  :

**Comment by faxm0dem** [comment]
The same issue would appear with any dynamically created parent stream. As the child cannot choose its parent (pun intended), it would seem sanest to me to let the user choose a function instead of a static `:stream-name` *e.g.* `#(str (:host %) (:service %))` in your example

**Comment by faxm0dem** [comment]
or use `by-fn` / `by-builder` instead

**Comment by mcorbin** [comment]
I thought about using a function instead of a keyword in :stream-name but it can cause others issues. If i have :

```clojure
(defn my-stream
  []
  (coalesce {:dt 1 :stream-name #(str (:host %) (:service %))}))
```
I can use my-stream in a ```by [:host :service]````stream but not in a standard stream (without by) because :host and :service are changing.

I think i will revert my PR on coalesce state for now.
