### ISSUE TITLE
[Question] Callbacks that runs periodically

### ISSUE THREAD

**Issue by liuweichu** [riemann/riemann#759]
When I write functions in `streams`, they are hooked on new event arrives.

How can I implement a function that can be triggered periodically? For example, I want to have a report function that runs every 5 minutes, looking into index and generate a summary event?

**Comment by mcorbin** [comment]
You can use the [part-time-simple](https://github.com/riemann/riemann/blob/master/src/riemann/streams.clj#L562) stream. You can look how this stream is used in streams.clj.

**Comment by faxm0dem** [comment]
you can also use [services](http://riemann.io/api/riemann.core.html#var-conj-service) you can find an example for riemann's [instrumentation](https://github.com/riemann/riemann/blob/master/src/riemann/config.clj#L122-L132).

**Comment by liuweichu** [comment]
@mcorbin @faxm0dem Thanks very much!

**Comment by faxm0dem** [comment]
BTW we prefer the Google group or IRC for questions instead of opening issues
