### ISSUE TITLE
Accept more Twilio params and do not force 'from'

### ISSUE THREAD

**Issue by jeromer** [riemann/riemann#761]
The twilio plugin seems to force the `from` param here https://github.com/riemann/riemann/blob/0.2.12/src/riemann/twilio.clj#L75 

The problem is when you use a dedicated `MessagingServiceSid` then you are require to send it instead of `from` as explained here : https://www.twilio.com/docs/api/rest/sending-messages#post-parameters-conditional 

Since `from` is forced in the twilio plugin the `MessagingServiceSid` is not used which is problematic.

I propose to stop forcing the `from` argument in the Twilio plugin and to let users configure it manually in their own Riemann config. This way only Twilio's credentials (`account` and `service-key`) are mandatory. The rest is up to the user.

What do you think ?

:)

**Comment by mcorbin** [comment]
Hi,

I don't know how twilio works but you're probably right. I think we must keep the default :from option (for backward compatibility), but remove it when MessagingServiceSid is configured.

I will look at this soon.

**Comment by jeromer** [comment]
How about something like this pseudo code (my clojure is terrible):
```
IF from == "" AND other any other options provided THEN
   remove from from the request and add all the other options provided
ELSE
   use (or force) from as usual
FI
```
That way there is no BC break and anyone who want to send specific options the Twilio is not blocked is `from` is optional/forbidden/else.

What do you think ?

:)

**Comment by mcorbin** [comment]
Actually, i am doing something like
```
IF-NOT (from exists OR MessagingServiceSid exists) THEN
    Add {:from "+15005550006"} for compatibility
ELSE
    Use from and/or MessagingServiceSid parameters.
```

I will also try to add more API options (MediaUrl, StatusCallback...) to the twilio stream (actually, only :from and :body options are used).

**Comment by mcorbin** [comment]
My PR should fix it. Is it possible for you to test my PR using MessagingServiceSid ?
