### ISSUE TITLE
Reload not working on RHEL 7.1

### ISSUE THREAD

**Issue by mcorbin** [riemann/riemann#780]
Linux distribution : Red Hat Enterprise Linux Server release 7.1 (Maipo)

After installing the Riemann RPM:

```
# service riemann reload
Reloading riemann configuration (via systemctl):  Failed to reload riemann.service: Job type reload is not applicable for unit riemann.service.
                                                           [FAILED]
# systemctl reload riemann
Failed to reload riemann.service: Job type reload is not applicable for unit riemann.service.
```

So i cannot reload Riemann on rhel (stop/start is working).

**Comment by pradeepchhetri** [comment]
By looking at the error, It looks like we aren't currently pushing systemd init script and the one getting generated automatically doesn't support reload. @mcorbin may i ask you to show the `riemann.service` file inside somewhere `/lib/systemd/system/`

**Comment by jamtur01** [comment]
There is no systemd script - #633

**Comment by mcorbin** [comment]
I don't understand why, in Debian 8, `service riemann reload` or `systemctl reload riemann` works and not in RHEL. There is no systemd service file in the debian installer too.

**Comment by pradeepchhetri** [comment]
I debugged the issue further.

Looks like the `systemd-sysv-generator` tool (provided by `systemd-sysv` package) which converts the sysvinit script to systemd script adds `ExecReload` config in Debian8 but not in Redhat7. Both have different version of `systemd` installed, maybe that is causing it.

Here is the commands and their logs for your reference: https://gist.github.com/pradeepchhetri/77cc8f6feabb1eb1d740117f13a562fc

**Comment by mcorbin** [comment]
Thanks ;) I was going to post the output of `systemctl cat riemann` on both RHEL and Debian, and effectively ExecReload is missing on RHEL/Centos. 

We should probably package Riemann for both systemd/sysvinit, but after reading #633 i'm not sure what is the best way to do it (2 differents rpms with/without the systemd unit and the daemonize dependency, force the deamonize dependency even when it is not used... ?).

**Comment by pradeepchhetri** [comment]
I am not sure why we are using `daemonize` instead of `daemon` which i see commented out. Here are few of the projects which are using `daemon`

https://github.com/DataDog/dd-agent/blob/master/packaging/centos/datadog-agent.init#L145
https://github.com/OpenTSDB/tcollector/blob/master/rpm/initd.sh#L74

I think we should have only one RPM and one DEB. I will have a look how https://github.com/jordansissel/fpm manages the different init system internally for the same distribution.

**Comment by jamtur01** [comment]
Happy to have someone provide a patch that addresses this and #633 .
