### ISSUE TITLE
gh-pages: quickstart, syntax highlighting bug 

### ISSUE THREAD

**Issue by sudoankit** [riemann/riemann#796]
The quickstart guide has this nasty out of code block render.

<img width="924" alt="screen shot 2017-04-02 at 12 54 43" src="https://cloud.githubusercontent.com/assets/8577076/24585273/3a375aee-17a4-11e7-8990-2fd64d4088bf.png">

I fixed it with some changes in CSS and now looks like:
<img width="846" alt="screen shot 2017-04-02 at 13 01 41" src="https://cloud.githubusercontent.com/assets/8577076/24585284/988abff0-17a4-11e7-885c-1b7660c4e011.png">

Should I go for a PR?

**Comment by faxm0dem** [comment]
:+1:

**Comment by sudoankit** [comment]
Alright. 
Thank you.

**Comment by mcorbin** [comment]
@sudoankit I still have the issue in riemann.io. 
The website is also smaller (smaller width, smaller font...) than before.

@jamturn01 can you reopen the issue (and maybe revert the commit if i'm right about the websize width) ?

**Comment by jamtur01** [comment]
I'm not seeing the smaller site. The long URL is still not wrapping though.

**Comment by mcorbin** [comment]
I have a smaller website on my machine (using jekyll serve, without the commit).

**Comment by sudoankit** [comment]
@jamtur01 Can you post a screenshot of the long URL which is not wrapping?

I see it's working alright in mine?
<img width="1212" alt="screen shot 2017-04-07 at 21 48 54" src="https://cloud.githubusercontent.com/assets/8577076/24809117/2111291e-1bdc-11e7-9445-8f0b9ad84de2.png">

**Comment by jamtur01** [comment]
![screenshot 2017-04-07 12 20 58](https://cloud.githubusercontent.com/assets/4365/24809170/b3d58f42-1b8c-11e7-8fd5-2f3e57c06e4b.jpg)

Chrome on OSX.

**Comment by mcorbin** [comment]
Firefix 52/Linux, when i am at the top of the quickstart on riemann.io, the last line i see is :
"Riemann is now listening for events. Install the Ruby client, utility package, and dashboard. You may need to install ruby-dev for some dependencies; your OS package manager should have a version available for your Ruby install."

On my machine without the commit, the last line i see is :
"You can also install Riemann via the Debian or RPM packages, through Puppet, Vagrant, or Chef."

So i have a bigger website locally.
I don't know if it is a problem (i don't have frontend skills).

**Comment by sudoankit** [comment]
@jamtur01 Alright. I reproduced that on Chrome OSX. Safari works alright.  I found a solution [http://stackoverflow.com/questions/10743763/word-wrap-break-word-does-not-work-in-this-example](url) here, let me fix this and test in all browsers.

**Comment by jamtur01** [comment]
@sudoankit I also updated the versions in quickstart so do a pull first.

**Comment by jamtur01** [comment]
Did you get a chance to test a solution?

**Comment by thachmai** [comment]
I propose 2 possible fixes: #864 and #

**Comment by jamtur01** [comment]
Then let's go with #864 - thanks for doing this!
