### ISSUE TITLE
Riemann-health not working

### ISSUE THREAD

**Issue by srikanthdixit** [riemann/riemann#809]
Hello,

I would like to implement "grafana" in server. For that, i'm using "influxdb and riemann" i installed and configured grafana, influxdb and riemann. But when i try to use riemann-health i'm not getting any output. But, i can see server's info ex: when i use "select * from cpu" in influxdb shell i'm getting the data. But not for riemann-health. Please suggest me if i'm wrong.

**Comment by jamtur01** [comment]
Can you tell me a bit more about your issue? How are you running riemann-health?

**Comment by srikanthdixit** [comment]
Just i'm giving "riemann-health" not getting any out put. Is this the way to run riemann-health ?

**Comment by jamtur01** [comment]
And you have a local Riemann daemon running? By default with no options `riemann-health` tries to connect to a Riemann server on IP `127.0.0.1` on port `5555`.

**Comment by srikanthdixit** [comment]
<img width="646" alt="screen shot 2017-04-19 at 11 23 47 am" src="https://cloud.githubusercontent.com/assets/26823541/25195549/cc5ea82c-24f2-11e7-9baf-01a5a7c480e8.png">

**Comment by jamtur01** [comment]
What's the configuration of that Riemann server?

**Comment by srikanthdixit** [comment]
You can see above attached screen shot, 
<img width="325" alt="screen shot 2017-04-19 at 11 25 24 am" src="https://cloud.githubusercontent.com/assets/26823541/25195601/f7e18c08-24f2-11e7-9e7f-dc223a199e34.png">

**Comment by srikanthdixit** [comment]
when i type riemann-health i'm like this

**Comment by jamtur01** [comment]
No - `riemann-health` just emits events to a Riemann server. What's the configuration of your Riemann SERVER. Where are you expecting to see the events?

**Comment by srikanthdixit** [comment]
Please find below is the riemann.conf which i configured with influxdb

[root@kd58 etc]# vi riemann.config

; -*- mode: clojure; -*-
;; InfluxDB database details where Riemann will store the data. Setup :username and :password
;; if you added security step behind riemann database access.
(def influxdb-creds {
     :version :0.9
     :host "localhost"
     :port 8086
     :db "riemann"
     ; :username "riemann"
     ; :password "riemann_password"
})

(def influxBatchSender
  (batch 100 1/10
         (async-queue! :agg {:queue-size 1000
                             :core-pool-size 1
                             :max-pool-size 4
                             :keep-alive-time 60000}
                       (influxdb influxdb-creds))))

; vim: filetype=clojure

(logging/init {:file "/root/riemann-0.2.12/riemann.log"})

; Listen on the local interface over TCP (5555), UDP (5555), and websockets
; (5556)
(let [host "0.0.0.0"]
  (tcp-server {:host host})
  (udp-server {:host host})
  (ws-server  {:host host}))

; Expire old events from the index every 5 seconds.
(periodically-expire 60)

(let [index (index)]
  ; Inbound events will be passed to these streams:
  (streams
    (default :ttl 60
      ; Index all events immediately.
      index

      ; Log expired events.
       (expired
        (fn [event] (info "expired" event))))))

**Comment by jamtur01** [comment]
I don't see you sending any events to Influx in that configuration? You need to actually specify `influxBatchSender` in the `streams` to actually trigger the send.

**Comment by srikanthdixit** [comment]
Actually i'm new to riemann. Could you please include some events and add into that configuration file which i sent and send it to me.

**Comment by jamtur01** [comment]
See the HOWTO for more help - http://riemann.io/howto.html#forward-to-influxdb

**Comment by srikanthdixit** [comment]
I did include events as you said in riemann.conf


[root@kd58 etc]# vi riemann.config

; -*- mode: clojure; -*-
;; InfluxDB database details where Riemann will store the data. Setup :username and :password
;; if you added security step behind riemann database access.
(def influx (influxdb { :host "localhost"
                        :db "riemann"
                        :version :new-stream}))

(streams
 (smap
  (fn [event]
    (assoc event :measurement     (:service event)
                 :influxdb-tags   {:state  (:state event)}
                 ;; :value = 0 by default
                 :influxdb-fields {:value (or (:metric event) 0)}))
      influx))

; vim: filetype=clojure

(logging/init {:file "/root/riemann-0.2.12/riemann.log"})

; Listen on the local interface over TCP (5555), UDP (5555), and websockets
; (5556)
(let [host "0.0.0.0"]
  (tcp-server {:host host})
  (udp-server {:host host})
  (ws-server  {:host host}))

; Expire old events from the index every 5 seconds.
(periodically-expire 60)

(let [index (index)]
    (default :ttl 60
      ; Index all events immediately.
      index

      ; Log expired events.
       (expired
        (fn [event] (info "expired" event)))))

When try to restart riemann/riemann.conf getting below error and couldn't start it show "Illegal Argument error"
ERROR:


[root@kd58 etc]# /root/riemann-0.2.12/bin/riemann /root/riemann-0.2.12/etc/riemann.config
INFO [2017-04-19 13:57:09,193] main - riemann.bin - PID 23028
INFO [2017-04-19 13:57:09,197] main - riemann.bin - Loading /root/riemann-0.2.12/etc/riemann.config
ERROR [2017-04-19 13:57:09,218] main - riemann.bin - Couldn't start
clojure.lang.Compiler$CompilerException: java.lang.IllegalArgumentException: No matching clause: :new-stream, compiling:(riemann.config:4:13)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3657)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:451)
	at clojure.lang.Compiler.eval(Compiler.java:6932)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.lang.RT$3.invoke(RT.java:320)
	at riemann.config$include.invokeStatic(config.clj:412)
	at riemann.config$include.invoke(config.clj:390)
	at riemann.bin$_main.invokeStatic(bin.clj:99)
	at riemann.bin$_main.invoke(bin.clj:85)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at riemann.bin.main(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No matching clause: :new-stream
	at riemann.influxdb$influxdb.invokeStatic(influxdb.clj:223)
	at riemann.influxdb$influxdb.invoke(influxdb.clj:186)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3652)
	... 12 common frames omitted

**Comment by mcorbin** [comment]
Hi,

Do you hi Riemann 0.2.13 ?

2017-04-19 20:59 GMT+02:00 srikanthdixit <notifications@github.com>:

**Comment by jamtur01** [comment]
You might need to checkout the current InfluxDb docs http://riemann.io/api/riemann.influxdb.html

**Comment by srikanthdixit** [comment]
@mcorbin  I'm using Riemann 0.2.12

**Comment by mcorbin** [comment]
The new stream (in the documentation) is only supported in 0.2.13.

**Comment by srikanthdixit** [comment]
ok then what i can do for 0.2.12 ?

**Comment by mcorbin** [comment]
Use `:version :0.9`, and add a `:tag-fields` option. From the documentation:

```
:tag-fields A set of event fields to map into InfluxDB series tags. (default: #{:host}).
```

Don't use `smap` in your stream, no need to format events with the old stream.

**Comment by srikanthdixit** [comment]
You meant to say use influxdb version :0.9 ? Currently I'm using Influxdb 1.2.0

**Comment by mcorbin** [comment]
Yes, but using the :0.9 version in the stream should work with influx 0.9 and higher

**Comment by srikanthdixit** [comment]
I added :tag-field option as you suggest but still riemann is not starting. Please find below is my "riemann.conf" whether i added correct or not. If not can you please modify from you end and send it me that would be more helpful.


[root@kd58 etc]# vi riemann.config

; -*- mode: clojure; -*-
;; InfluxDB database details where Riemann will store the data. Setup :username and :password
;; if you added security step behind riemann database access.
(def influx (influxdb { :host "localhost"
                        :db    "riemann"
                        :version :0.9}))

          **`:tag-fields`     A set of event fields to map into InfluxDB series tags.
                            (default: `#{:host}`).

          Each event can have these keys :
          `:tag-fields`     A set of event fields to map into InfluxDB series tags..
          `:precision`       The time precision. Possibles values are `:seconds`, `:milliseconds` and `:microseconds` (default `:seconds`). The event `time` will be converted."**

(streams
  (fn [event]
    (assoc event :measurement     (:service event)
                 :influxdb-tags   {:state  (:state event)}
                 ;; :value = 0 by default
                 :influxdb-fields {:value (or (:metric event) 0)}))
      influx))

; vim: filetype=clojure

(logging/init {:file "/root/riemann-0.2.12/riemann.log"})

; Listen on the local interface over TCP (5555), UDP (5555), and websockets
; (5556)
(let [host "0.0.0.0"]
  (tcp-server {:host host})
  (udp-server {:host host})
  (ws-server  {:host host}))

; Expire old events from the index every 5 seconds.
(periodically-expire 60)

(let [index (index)]
    (default :ttl 60
      ; Index all events immediately.
      index

      ; Log expired events.
       (expired
        (fn [event] (info "expired" event)))))

**Comment by mcorbin** [comment]
I don't understand how your message is formatted.

**Comment by jamtur01** [comment]
Closed pending response.
