### ISSUE TITLE
Need directory paths for riemann rpm in RHEL 7.2

### ISSUE THREAD

**Issue by Rajeshkumar123** [riemann/riemann#817]
I have installed riemann-0.2.13-1.noarch.rpm in my RHEL machine version 7.2 . After installation I couldn't find the setup files in usual directory path. I can find the riemann.config file under /etc/riemann where I can find the riemann setup folder or under which folder I can find the riemann files to configure the setup.

Can anyone provide me those directory paths it would be a great help

**Comment by mcorbin** [comment]
Hi

```
rpm -qlp riemann-0.2.13-1.noarch.rpm
/etc/init.d/riemann
/etc/riemann
/etc/riemann/riemann.config
/etc/sysconfig/riemann
/usr/bin/riemann
/usr/lib/riemann/riemann.jar
/var/log/riemann
```

**Comment by Rajeshkumar123** [comment]
@mcorbin .. Thank you much for your timely response. Let me check it out

**Comment by mcorbin** [comment]
`rpm -install` installs the package, `rpm -qlp" lists files in the package (-q = query, -l = list, -p = package).

**Comment by Rajeshkumar123** [comment]
@mcorbin .. Thank you
