### ISSUE TITLE
Email not getting triggered in logstash 5.2.1

### ISSUE THREAD

**Issue by Rajeshkumar123** [riemann/riemann#819]
Hi,

I was using logstash 2.3.0 with logstash-output-riemann-2.0.5 and riemann-client-0.2.1 and riemann 0.2.10. it was working awesome without any issues. Now I have upgraded it to logstash 5.2.1 with logstash-output-riemann-3.0.0 and riemann-client-0.2.1 and riemann-0.2.13 here I am not getting any emails it's ot showing any errors also. 

Can you please provide any details related to this

**Comment by mcorbin** [comment]
Hi,

Did you receive the events from Logstash in Riemann ? Could be a problem with the logstash output riemann.

**Comment by Rajeshkumar123** [comment]
The riemann logs not writing anything except startup message. I hope events are not sending it to Riemann. Is mtrc gem is required to install in logstash?

**Comment by boernd** [comment]
Hi,

I cannot reproduce your issue. Tested with LS5.2.1 and riemann output installed.

Logstash config:
```
input {
    stdin {
        codec => json
    }
}

output {
    riemann {
        map_fields => true
    }
}
```

Riemann config:
```
(let [index (index)]
  ; Inbound events will be passed to these streams:
  (streams
    #(info %)))
```
`{"service": "test", "metric": 10}` results in:

`INFO [2017-05-19 10:39:27,450] defaultEventExecutorGroup-2-2 - riemann.config - #riemann.codec.Event{:host xyz, :service test, :state nil, :description nil, :metric 10, :tags nil, :time 1495183167, :ttl nil}`

**Comment by Rajeshkumar123** [comment]
@boernd can you please give me
1.  The list of version of this plugins logstash-output-riemann, riemann-client 
2. Version of riemann componet you have installed 
3. Can you please check whether the gem file mtrc is installed in your logstash

**Comment by boernd** [comment]
logstash-output-riemann-3.0.0
riemann-client-0.2.1
riemann-0.2.14-SNAPSHOT
mtrc-0.0.4

**Comment by Rajeshkumar123** [comment]
Here is my Logstash output config

```
riemann{
		host => "xx.xx.xx.xxx"
		port => 5555
	   riemann_event =>  {
						"service" => "Op"
						"description" => "%{CC_Keyword}"
						"type" => "%{type}"
						"metric" => "%{metric}"
						"ttl" => "%{ttl}"						
                     }		
	}
```

My Riemann Config

```
(logging/init {:file "/logs/riemann_logs/riemann.log"})

  (tcp-server {:host "xx.xx.xx.xxx" :port 5555})
  
  ;Create index and print the values indexed
  (let [customerindex (default :ttl 300 (update-index (index)))])


  (let [email (mailer {:host "xxxxx"
							:port 25
							:user "xxxxx"
							:pass "xxxxx"
							:auth "true"
							:subject (fn [events] "ssssss")
							:body (fn [events] "sssssss")
							:from "sss@ss.com"})]
  (streams
    (where (service "Op")
 ;Check for every 120sec events
      (fixed-time-window
        120
        (smap
          (fn [events]
            (let [count-of-failures (count (filter #(= "WARN" (:CC_Keyword %)) events))] ;Calculate the count for matched value
              (event
                {:status "Error Failures"
                 :metric  count-of-failures 
                 :total-fail (> count-of-failures 1)})))  
				 
          (where (and (= (:status event) "Error Failures")
                      (:total-fail event))
				(rollup 1 120
            (email "ssss@ss.com")))prn)))))
```

In my logstash mtrc gem is missing

**Comment by Rajeshkumar123** [comment]
Now I have installed mtrc also. Let me check the code you tried ..

**Comment by jamtur01** [comment]
Please re-open if issues continue.
