### ISSUE TITLE
Riemann output support multi graphite?

### ISSUE THREAD

**Issue by keyboardfann** [riemann/riemann#820]
Dear All,
    I have two graphite server and want to set up Riemann output to these two Graphite servers.  Does riemann support multi-graphite server setting?

**Comment by faxm0dem** [comment]
riemann stream functions accept multiple child streams, so you can of course send to multiple graphite servers

```
(streams
  graphite1 graphite2 ... elasticsearch1 ...)
```

**Comment by keyboardfann** [comment]
Dear @faxm0dem ,
    I write it like this. let me confirm, it means the metrics will round-robin to the two graphtie servers. Is it right?

```
(where  (service #"^riemann ")
  (graphite {:host "tng1398"
             :port 2013} )
  (graphite {:host "tng1399"
             :port 2013} ))
```

**Comment by mcorbin** [comment]
@keyboardfann Nope, in this example all events matching the regex will be send to both graphite servers. In Riemann, events are "copied" to all children (exactly like in your previous issues where you used "kafka-output" and "graphite").

**Comment by keyboardfann** [comment]
Dear @mcorbin ,
   Ok, Is riemann can do metrics dispatch like Round-Robin? Or I should have a Loadbalance VIP connect to the two graphite and set riemann output to the VIP.

**Comment by mcorbin** [comment]
> Or I should have a Loadbalance VIP connect to the two graphite and set riemann output to the VIP

You should do this ;)

**Comment by keyboardfann** [comment]
Ok ~ I get the answer. Thank you.

**Comment by faxm0dem** [comment]
that being said, a RR stream would be cool
