### ISSUE TITLE
[Feature Request]  Add support for routing SNMP events 

### ISSUE THREAD

**Issue by Phil12026** [riemann/riemann#824]
Right now the only thing that seems to support getting SNMP events (for proprietary switches and routers) is the himpy plugin which appears to be abandoned since it's Github page returns a 500 error.  Anyone know of a way to gatherer SNMP events through Riemann so they can then be routed?

**Comment by jamtur01** [comment]
Looks good to me - https://github.com/pyr/himpy.

**Comment by Phil12026** [comment]
Your link seems to work, so probably just a bad link in the riemann website.  Thanks so much @jamtur01

**Comment by jamtur01** [comment]
Actually I think GH was having issues. The link in the docs is fine. Cool.
