### ISSUE TITLE
How to have dynamic set of email users configured to send notifications based on Alert Rules?

### ISSUE THREAD

**Issue by jait-23** [riemann/riemann#826]

**Comment by mcorbin** [comment]
Hi,

probably something like:
```clojure

(def mailer
  "send a mail"
  (riemann.test/io
    (mailer {:host "foo"
             :port 25
             :from "riemann@foo.foo"
             :subject #(mail-subject %)
             :body #(mail-body %)})))

(defn email
  [address]
  (mailer address))

(streams
  (where (...)
    (email "foo@riemann.io"))
  (where (...)
    (email "bar@riemann.io"))
  ...
  )
```

**Comment by jait-23** [comment]
Hello @mcorbin, thanks for the answer. But I have different set of email users for my different programs. Note, the users are not 3 or 4. They are many. Above 1000+. If I can call one API to fetch the users and use the email-ids from its response over here and pass to reimaan, event structure, it would be helpful. Do you have any suggestions on this?

**Comment by jamtur01** [comment]
Your configuration is just Clojure - you can write code to query the API with something like `clj-http`.

**Comment by jait-23** [comment]
@jamtur01 , Can you provide some more details or articles on this?

**Comment by jamtur01** [comment]
If you have an API that contains the email addresses and some criteria to select the specific addresses you could do something like:

```
(ns query_email
  (:require [clj-http.client :as client]))

(defn extractEmail
  [responseBody]
  (get (json/read-str responseBody) "email"))

(defn getEmail
  [url input]
   (:body
    (client/get url
                {:query-params {"email" input}})))

. . .  blah.
```

Then call that when sending the notifications to populate the addresses...

https://github.com/dakrone/clj-http
https://mmcgrana.github.io/2010/08/clj-http-clojure-http-client.html

**Comment by mcorbin** [comment]
@jait-23 Do you need more help ?

**Comment by jamtur01** [comment]
Closing.
