### ISSUE TITLE
java.lang.NullPointerException: null in Riemann

### ISSUE THREAD

**Issue by Rajeshkumar123** [riemann/riemann#834]
I have installed riemann-0.2.13-1.noarch as RPM service. I am sending the events from logstash 5.2.1 and the plugin I have installed is logstash-output-riemann-3.0.0 I wrote the below riemann code to trigger an email. I am getting exception. Please point me where I am going wrong.

**Riemann Config:**

```
(let [email (mailer {:host "XXXXX"
                            :port 25
                            :subject (fn [events] "Consecutive login failed")
                            :body (fn [events] "Hello Team, \n \n There are more consecutive logins failure occured @" (riemann.common/time-at (:timestamp event))"")
                            :from "XXXX"})]
  (streams
 ;Check for every 120sec events
      (fixed-time-window
        120
        (smap
          (fn [events]
            (let [count-of-failures (count (filter #(re-find #"com.thed.server.access.Exception. Please reset credentials for user. Last error occurred was:Authentication failed, please check user credentials*" (:message %)) events))] ;Calculate the count for matched value
              (event
                {:status "Class failures"
                 :metric  count-of-failures 
                 :total-fail (> count-of-failures 1)})))  

          (where (and (= (:status event) "Class failures")
                      (:total-fail event))
            (rollup 1 120
            (email "xxx","xxx","xxx")
            ))prn))))
```

**Error:**

```
WARN [2017-07-06 17:45:49,204] defaultEventExecutorGroup-2-1 - riemann.streams - riemann.streams$smap$stream__6639@55d73fdc threw
java.lang.NullPointerException: null
    at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
    at java.util.regex.Matcher.reset(Matcher.java:309)
    at java.util.regex.Matcher.<init>(Matcher.java:229)
    at java.util.regex.Pattern.matcher(Pattern.java:1093)
    at clojure.core$re_matcher.invokeStatic(core.clj:4674)
    at clojure.core$re_find.invokeStatic(core.clj:4716)
    at clojure.core$re_find.invoke(core.clj:4716)
    at riemann.config$eval88$fn__93$fn__94.invoke(riemann.config:48)
    at clojure.core$filter$fn__4812.invoke(core.clj:2708)
    at clojure.lang.LazySeq.sval(LazySeq.java:40)
    at clojure.lang.LazySeq.seq(LazySeq.java:49)
    at clojure.lang.RT.seq(RT.java:521)
    at clojure.lang.RT.countFrom(RT.java:625)
    at clojure.lang.RT.count(RT.java:618)
    at riemann.config$eval88$fn__93.invoke(riemann.config:48)
    at riemann.streams$smap$stream__6639.invoke(streams.clj:161)
    at riemann.streams$fixed_time_window_fn$stream__6889$fn__6922.invoke(streams.clj:374)
    at riemann.streams$fixed_time_window_fn$stream__6889.invoke(streams.clj:374)
    at riemann.core$stream_BANG_$fn__8578.invoke(core.clj:19)
    at riemann.core$stream_BANG_.invokeStatic(core.clj:18)
    at riemann.core$stream_BANG_.invoke(core.clj:14)
    at riemann.transport$handle.invokeStatic(transport.clj:171)
    at riemann.transport$handle.invoke(transport.clj:165)
    at riemann.transport.tcp$tcp_handler.invokeStatic(tcp.clj:95)
    at riemann.transport.tcp$tcp_handler.invoke(tcp.clj:88)
    at riemann.transport.tcp$gen_tcp_handler$fn__11550.invoke(tcp.clj:66)
    at riemann.transport.tcp.proxy$io.netty.channel.ChannelInboundHandlerAdapter$ff19274a.channelRead(Unknown Source)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
    at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:363)
    at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
    at java.lang.Thread.run(Thread.java:745)
```

**Note:** The above code is working fine in `0.2.10` but its not sending emails when I updated to `0.2.13`

**Comment by moshe** [comment]
Try to filter expired events.
**my guess:**
your events getting expired, then getting into re-find with `null` (expired event don't save custom attributes by default).
more info:
http://riemann.io/api/riemann.streams.html#var-expired
http://riemann.io/concepts.html

> Events entered into the index have a :ttl field which indicate how long that event is valid for. Events that sit in the index for longer than their TTL are removed from the index and reinserted into the event streams with state "expired". Instead of polling for failure, just let events expire. Services which fail to check in regularly can be handled by the same state-transition streams you use for error handling.

**Comment by Rajeshkumar123** [comment]
@moshe Shall I try the :ttl from the code?

**Comment by moshe** [comment]
No, just filter out the expired events if you don't use them by something like:
```
(where* #(not (expired? %))
...
)
```

**Comment by Rajeshkumar123** [comment]
I have updated my code as per your suggestion but still I am getting the same error.

```
(let [email (mailer {:host "XXXXX"
                            :port 25
                            :subject (fn [events] "Consecutive login failed")
                            :body (fn [events] "Hello Team, \n \n There are more consecutive logins failure occured @" (riemann.common/time-at (:timestamp event))"")
                            :from "XXXX"})]
  (streams
 ;Check for every 120sec events
      (fixed-time-window
        120
        (smap
          (fn [events]
           (where #(not (expired? %))
            (let [count-of-failures (count (filter #(re-find #"com.thed.server.access.Exception. Please reset credentials for user. Last error occurred was:Authentication failed, please check user credentials*" (:message %)) events))] ;Calculate the count for matched value
              (event
                {:status "Class failures"
                 :metric  count-of-failures 
                 :total-fail (> count-of-failures 1)}))))

          (where (and (= (:status event) "Class failures")
                      (:total-fail event))
            (rollup 1 120
            (email "xxx","xxx","xxx")
            ))prn))))
```

**Comment by Rajeshkumar123** [comment]
@moshe 
I tried different scenario just to validate. I have utlised another filter as below and I didn't get any error as mentioned above

` (let [count-of-failures (count (filter #(= "com.thed.server.access.Exception. Please reset credentials for user. Last error occurred was:Authentication failed, please check user credentials*" (:message %)) events))]`

But I am getting error when I utilize only `re-find` filter

` (let [count-of-failures (count (filter #(re-find #"com.thed.server.access.Exception. Please reset credentials for user. Last error occurred was:Authentication failed, please check user credentials*" (:message %)) events))]`

Please advice whether the re-find filter is removed or is there any other way to use regex to satisfy my requirement.

**Comment by faxm0dem** [comment]
I think what might cause your Exceptions is when events without `:message` enter the stream.
The reason for the different behaviour between `=` and `re-find` predicate is illustrated through this repl session:

```
user=> (def foo {:a "a" :b "b"})
#'user/foo
user=> foo
{:a "a", :b "b"}
user=> (= "a" (:a foo))
true
user=> (= "a" (:c foo))
false
user=> (re-find #"a" (:a foo))
"a"
user=> (re-find #"a" (:c foo))

NullPointerException   java.util.regex.Matcher.getTextLength (Matcher.java:1283)
user=>
```

So you simply need to filter the stream for messages containing the `:message`key

**Comment by Rajeshkumar123** [comment]
@faxm0dem Thank for the explanation it really helps me to understand. So whenever my message contains a expected value then I will get an email alert. If there is no event matching my re-find section at that time I will get this nullpointer exception right?

**Comment by Rajeshkumar123** [comment]
@faxm0dem 
For validation purpose I have changed my code to the following format
```
(let [email (mailer {:host "XXXX"
							:port 25
							:subject (fn [events] "OutOfMemoryError ")
							:body (fn [events] (format-body-server events))
							:from "ELM@toyota.com"})]
  (streams
          (where (:event_status #"WA*")
            (email "xx","xx","xx","xx")
			)prn))
```

Now also email not triggering and I am not getting any error. Please correct me if any updates need to be done on the coding section.

**Comment by faxm0dem** [comment]
LGTM

**Comment by mcorbin** [comment]
I think it's not working ;)
`where (:event_status #"WA*")` => It will be always nil.

You should probably do

```clojure
(where :event_status ;; check if event_status is present
   (where (re-find #"WA*" (:event_status event)) ;; check with re-find the regex
 ...
```

**Comment by Rajeshkumar123** [comment]
@mcorbin @faxm0dem 

Its not working whenver I use 're-find ' I am getting error `NullpointerException` mentioned above in my first post

The `:log` field contains the value "INFO"

**Working:**
`(let [count-of-failures (count (filter #(= "INFO" (:log %)) events))]`

**Not Working:**
`(let [count-of-failures (count (filter #(re-find "INF*" (:log %)) events))]`

My requirement is to use regex pattern ..

**Comment by faxm0dem** [comment]
Try this: `(streams (where (:log event) count-of-failures))`

**Comment by Rajeshkumar123** [comment]
@faxm0dem  What it will do the code which you suggested above. I couldn't understand can you please explain me the functionality..

**Comment by faxm0dem** [comment]
it will pass only events containing the `:log` key to the `count-of-failures` child stream

**Comment by Rajeshkumar123** [comment]
@faxm0dem 

```
(let [email (mailer {:host "XXXXX"
                            :port 25
                            :subject (fn [events] "Consecutive login failed")
                            :body (fn [events] "Hello Team, \n \n There are more consecutive logins failure occured @" (riemann.common/time-at (:timestamp event))"")
                            :from "XXXX"})]
  (streams
(streams (where (:log event) count-of-failures))
      (fixed-time-window
        120
        (smap
          (fn [events]
           (where #(not (expired? %))
            (let [count-of-failures (count (filter #(re-find #"com.thed.server.access.Exception.*" (:message %)) events))] ;Calculate the count for matched value
              (event
                {:status "Class failures"
                 :metric  count-of-failures 
                 :total-fail (> count-of-failures 1)}))))

          (where (and (= (:status event) "Class failures")
                      (:total-fail event))
            (rollup 1 120
            (email "xxx","xxx","xxx")
            ))prn))))
```

Do you want me to update in this way?

**Comment by faxm0dem** [comment]
no, just replace the line with `(where (:log event)`

**Comment by faxm0dem** [comment]
BTW I suggest we move this discussion over to the [Google group](https://groups.google.com/forum/m/#!forum/riemann-users) which is more suited for support. github issues is more for bugs and issues, thanks!

**Comment by mcorbin** [comment]
@Rajeshkumar123 did you find the solution ?

**Comment by Rajeshkumar123** [comment]
@mcorbin  Nope still I am facing the same issue..

**Comment by mcorbin** [comment]
You are doing

```clojure
(streams
  (where (:log event) count-of-failures))
  (fixed-time-window ...)
```

What is the count-of-failures stream ?
Also, take a look at the indentation. You don't filter events without :log in fixed-time-window.

**Comment by jamtur01** [comment]
Please re-open if you have further feedback.
