### ISSUE TITLE
Java Classloading

### ISSUE THREAD

**Issue by boernd** [riemann/riemann#859]
Since Java8 PermGen is replaced by Metaspace which is unbounded by default. If you do a lot of Riemann index lookups the Metaspace keeps growing forever. I think these classes are related:

```
   8:        240847        3853552  clojure.lang.KeywordLookupSite
   9:         34279        3290784  clojure.lang.DynamicClassLoader
```

Maybe we should add the `-XX:MaxMetaspaceSize=` setting to the default JVM options so that users cannot run into this issue (since Java7 support is dropped)? I cannot get rid of the Full GCs though (`-XX:+CMSClassUnloadingEnabled` does not seem to help):

```
2017-10-02T11:09:37.494+0200: 698.070: [Full GC (Metadata GC Threshold) 2017-10-02T11:09:37.494+0200: 698.070: [CMS: 45615K->47330K(707840K), 0.3579119 secs] 297133K->47330K(1014528K), [Metaspace: 120625K->120625K(1144832K)], 0.3582312 secs] [Times: user=0.36 sys=0.01, real=0.36 secs]
2017-10-02T11:09:37.852+0200: 698.428: [Full GC (Last ditch collection) 2017-10-02T11:09:37.852+0200: 698.428: [CMS: 47330K->32857K(707840K), 0.2180059 secs] 47330K->32857K(1014528K), [Metaspace: 120625K->120625K(1144832K)], 0.2366470 secs] [Times: user=0.23 sys=0.00, real=0.24 secs]
```

Has anyone experience with the G1 collector & Riemann?

**Comment by mcorbin** [comment]
Hi,

I don't have a lot of experience with G1/JVM tuning, but i will try to reproduce your issue (it can take some time ;) ). You just use something like `(riemann.index/lookup index "host" "service)` to do index lookups ?

**Comment by boernd** [comment]
Yes exactly, a lot of index lookups should reproduce the issue (maintenance-window queries in our case). Without the `MaxMetaSpaceSetting` the resident memory size of the process should grow steadily.

**Comment by faxm0dem** [comment]
I might be running into this. How can I make sure?

**Comment by boernd** [comment]
You can check e.g. with `jcmd <riemann_pid> GC.class_histogram | grep clojure.lang.DynamicClassLoader >> /tmp/riemann.histo` if the instance count ever decreases (after e.g. CMS gc).

**Comment by faxm0dem** [comment]
@boernd arigato!

**Comment by mcorbin** [comment]
Ì tried to reproduce the issue with this conf

```clojure
(streams
 (index)
 (where (service #"^(riemann streams rate)") #(info %))
 (smap (fn [event]
         (riemann.index/lookup (:index @core) (:host event) (:service event)))))
```

I sent 15000 events/sec to Riemann and monitored it with visualvm. The number of loaded classes does not increase in time (verified with visualvm and the jcmd command you provided), but i see the metaspace grow slowly (+ 0.18mb in ~ 1 hour).

I don't really know what to do now ^^

**Comment by mcorbin** [comment]
@boernd maybe related to https://github.com/riemann/riemann/issues/312 ?

**Comment by boernd** [comment]
@mcorbin Thx, seems related. I'm not 100% sure yet what exactly in my config causes this behavior. I also cannot reproduce e.g. with the maintenance examples mentioned in the Howto guide.

This is my maintenance function:

```
(defn maintenance-mode?
  "Is target/host/service currently in maintenance?"
  [event]
  ; Take an expression representing a query for maintenance mode
  (io (->>
        (list 'and
          (list 'or
            (list '= :host (:host event))
            '(= :host (str (:targetid event) ".all")))
          (list 'or
            '(= :service "maintenance")
            (list '= :service (str "maintenance." (:service event))))
          (list '= :projectid (:projectid event))
          (list '= :targetid (:targetid event)))
        ; Search the current Riemann core's index for any matching events
        (riemann.index/search (:index @core))
        first
        :state
        (= "running"))))
```

And this is my Classloading/Metaspace GC behavior on one of the servers with `MaxMetaspaceSize` set to `312m`:
![riemann_cms](https://user-images.githubusercontent.com/807734/33420164-e4d80238-d5ad-11e7-9701-99b93c9ebdd4.png)

I also testet the `G1GC` collector but it does not make a difference I think. `CMS` and `G1GC` use a stop the world Full GC to clean up the metaspace.

**Comment by mcorbin** [comment]
I do not know either, i will try your configuration and see if i can find something.

Btw, i wrote for my company a maintenance-mode stream too, and like you we have keys like project etc...
But i wrote it to only query the index using host and service (so no query generated).

For example, my maintenance event in the index could have host = "my.host" and service = "maintenance-(:service event)-(:project event)". If i want to put a project in maintenance, i will have an event like host = nil and service = "maintenance-(:project event). I think it is better for performances to only do lookup on host/service because a query will scan the entire index for each event.

**Comment by mcorbin** [comment]
Additionally, i think you cannot reproduce it with the maintenance-mode stream from the doc because this stream only query on host on service. Riemann will detect that and do a simple lookup:

```clojure
(search [this query-ast]
        "O(n) unless the query is for exactly a host and service"
        (if-let [[host service] (query-for-host-and-service query-ast)]
          (when-let [e (.lookup this host service)]
            (list e))
          (let [matching (query/fun query-ast)]
            (filter matching (.values hm)))))
```

it's even better to can (lookup) directly instead of search if you know you only query on host/service, so riemann will not have to call  `query-for-host-and-service query-ast`.

**Comment by boernd** [comment]
Thx for your suggestions, closing...

**Comment by mcorbin** [comment]
Sorry to not be able to do more. You could also do something like

```clojure
(smap (fn [event]
        (let [values (seq index)]
          ;; filter/check the values
)))
```

But again you will scan the entire index (but no query will be generated).
