### ISSUE TITLE
Lein deps fails with lein 2.8.1

### ISSUE THREAD

**Issue by AndreaCrotti** [riemann/riemann#870]
I was having issues with one project that has Riemann as dependency where running `lein deps` would fail with this error:

```
Tried to use insecure HTTP repository without TLS.
This is almost certainly a mistake; however in rare cases where it's
intentional please see `lein help faq` for details.
```

I managed to isolate the problem to Riemann itself, since I can reproduce the same problem with a freshly checked out Riemann.
I don't see  see anything obviously wrong there but one of the dependencies clearly declares as source an HTTP server, which in newer version of Lein is not allowed.

**Comment by jamtur01** [comment]
Which dependency is that?

**Comment by AndreaCrotti** [comment]
I found it, it's actually this causing the issue:
https://github.com/bracki/clj-nsca/blob/master/project.clj

so `clj-nsca`
And it's a simple fix in theory, looks quite abandoned that project though

**Comment by jamtur01** [comment]
Added https://github.com/bracki/clj-nsca/pull/1.
