### ISSUE TITLE
Execute custom script on a state trigger / stream

### ISSUE THREAD

**Issue by pierrick-openIT** [riemann/riemann#899]
Hy,

it's possible to execute custom script on a state trigger or on a stream déclaration ?

regards ;)

**Comment by mcorbin** [comment]
Hi,

Riemann configuration is code, so if you can do it in Clojure/Java, you can do it in Riemann ;)

**Comment by mcorbin** [comment]
Example:

```clojure
(require '[clojure.java.shell :refer [sh]])

(streams
  (where (not (service #"^riemann "))
    (smap
      (fn [event]
        (info (sh "ls" "-la"))))))
```

What is your use case ?

**Comment by mcorbin** [comment]
@pierrick-openIT Do you need more help ? If not, can you close this issue ?
