### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by sgerrand** [riemann/riemann#901]
It has been a while since version 0.2.14 was released. There are many new changes which have been merged into master since then. Can they be released as a new version?

![Changes since v0.2.14](https://user-images.githubusercontent.com/203366/34938793-7f6e0b6a-f9e1-11e7-8871-e8268af44ff8.png)

**Comment by jamtur01** [comment]
I'll try to get to it next weekend.

**Comment by jamtur01** [comment]
See https://github.com/riemann/riemann/releases/tag/0.3.0
