### ISSUE TITLE
Opsgenie API v2

### ISSUE THREAD

**Issue by gmaurice** [riemann/riemann#918]
Hello,

The opsgenie api v1 will be shut down on June 30, 2018 as it's said at https://docs.opsgenie.com/docs/migration-guide-for-alert-rest-api
Are you aware of that ?

Thank you

**Comment by mcorbin** [comment]
I did not know that. I will try to update the opsgenie integration soon.

**Comment by gmaurice** [comment]
Great !
Thank you
