### ISSUE TITLE
adding a new tool

### ISSUE THREAD

**Issue by shmish111** [riemann/riemann#930]
I've created https://gitlab.com/shmish111/rcl in order to subscribe to events on the command line, you can use riemann queries and also `jq` so its working quite well. I was wondering if you wanted to put it on your website and also where do you recommend distributing it to as a package, currently its self-build so you need `stack` and `git` installed.

**Comment by jamtur01** [comment]
Hi! The riemann.io site docs are in this repo in the ghdocs branch and you can add tools and integrations yourself.
