### ISSUE TITLE
Is Riemann able to detect a service is up ??

### ISSUE THREAD

**Issue by Garyyyyy** [riemann/riemann#931]
Hi, I'm new to Riemann. I know Riemann can detect a service down by the changed-state condition. 
Is there any way to let Riemann immediately detect when a service is up ?? So that the endpoint client can know their service is up again?   Thank you !!

**Comment by jamtur01** [comment]
Have a look at the state transitions section in the Howto - http://riemann.io/howto.html#detect-state-transitions.

**Comment by jamtur01** [comment]
Also the best place for these sorts of questions is the mailing list: http://riemann.io/support.html.

Cheers!
