### ISSUE TITLE
folds/quotient-sloppy divides by zero

### ISSUE THREAD

**Issue by jstokes** [riemann/riemann#934]
The documentation for `folds/quotient-zero` states that 
> Like quotient, but considers 0/0 = 0.

However, the current implementation only checks that the first event's metric value is zero, and if so short circuits the `fold-all` over the rest of the metrics.  This doesn't actually protect against the divide by zero case when we have a non-zero metric followed by any number of zero metric events.

**Comment by jamtur01** [comment]
Thanks! Merged and released.
