### ISSUE TITLE
How to filter riemann-health to send only numeric metric for cpu event instead of all the process data.

### ISSUE THREAD

**Issue by shekaralle** [riemann/riemann#936]
I have multiple riemann-health on multiple hosts sending events to a riemann server machine.
And I am then sending events to Nagios.
But the problem is riemann-health sends cpu event data in a different format like with numeric metric in % and running process's data but I only need it to send % metric as my external application i.e. Nagios only requires metric and it is not able to process all the data.

Environment Details:
RHEL 7
Riemann-0.3.1

Following is my riemann.config file:

; -*- mode: clojure; -*-
; vim: filetype=clojure

(logging/init {:file "riemann.log"})

; Listen on the local interface over TCP (5555), UDP (5555), and websockets
; (5556)
(let [host "0.0.0.0"]
  (tcp-server {:host host})
  (udp-server {:host host})
  (ws-server  {:host host}))

; Expire old events from the index every 5 seconds.
(periodically-expire 5)

(let [index (index)]
  ; Inbound events will be passed to these streams:
  (streams
    (default :ttl 60
      ; Index all events immediately.
      index
      #(info %)
      ; Log expired events.
      )))

(let [nagios (nagios {:host "localhost" :port 5667 :password "Atos@1234" :encryption 1})]
  (streams
    (where (service "cpu")
             nagios)))

(let [nagios (nagios {:host "localhost" :port 5667 :password "1234" :encryption 1})]
  (streams
    (where (service "memory")
             nagios)))
(let [nagios (nagios {:host "localhost" :port 5667 :password "1234" :encryption 1})]
  (streams
    (where (service "disk /")
             nagios)))

**Comment by faxm0dem** [comment]
Hi, please use the google group for asking questions, and please don't cross-post.
I know it can be frustrating to wait for answers on google groups, as there are not many subscribers, and especially at this time of the year.
That being said, @aphyr already started to answer your question there, and I was planning to help you too ASAP.

Cheers

**Comment by shekaralle** [comment]
Thanks @faxm0dem
And can you help me in the Google group.
