### ISSUE TITLE
many netty warning in log file

### ISSUE THREAD

**Issue by avneradania** [riemann/riemann#937]
upgraded from 0.2.12 to 0.3.1-1 and since then, got many **netty** warnings:

INFO [2019-01-12 10:06:01,181] nioEventLoopGroup-5-25 - io.netty.channel.nio.NioEventLoop - Migrated 0 channel(s) to the new Selector.
....
WARN [2019-01-12 21:55:01,190] nioEventLoopGroup-5-14 - io.netty.channel.nio.NioEventLoop - Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@31c63c82.

anyone familiar with such warnings?

**Comment by jamtur01** [comment]
Hi - closing - please re-open if it's still an issue.
