### ISSUE TITLE
Getting data from influxDB to Riemann Streams to use the metrics ? 

### ISSUE THREAD

**Issue by bshah0408** [riemann/riemann#942]
I would like to have a function, which I can call through a query to influxDB and get the data and use it inside streams with smap function where I can calculate the average ? 

I like to compare the metric of current vs  metric of last day or last week so I need to call influx everytime for getting average value. 

Let me know any idea or function I can I create or use from Riemann would be very helpfull.

**Comment by boernd** [comment]
We made a Riemann plugin which periodically queries Elasticsearch instead of InfluxDB for historical data. Maybe you can get some inspiration from it: https://github.com/infonova/riemann-history

**Comment by jamtur01** [comment]
Hi - if you need additional help you can try the riemann mailing list - https://riemann.io/support.html.
