### ISSUE TITLE
Might need to rebuild RPM package for v0.3.2 

### ISSUE THREAD

**Issue by jamesdavidson** [riemann/riemann#946]
Hello!

I just tried to install Riemann on a 64-bit CentOS 7 virtual machine but got the following error from **yum**:

```
Transaction check error:
  package riemann-0.3.2-1.noarch is intended for a different operating system
```

I suspect this was caused by the packager running `lein pkg` on a macOS machine instead of a Linux machine but I am not sure.

```
# rpm -q --qf '%{os}\n' -p riemann-0.3.2-1.noarch.rpm
mac os x

# rpm -q --qf '%{os}\n' -p riemann-0.3.1-1.noarch.rpm
linux

# rpm -q --qf '%{os}\n' -p riemann-0.2.8-1.noarch.rpm
linux
```

Hopefully it is an easy fix! Thanks in advance

**Comment by jamtur01** [comment]
Argh. Sorry I thought I had transferred the RPMs and Debs from the Linux build box but it appears the script failed. Will fix now.

**Comment by jamtur01** [comment]
Give it a try now.

**Comment by jamesdavidson** [comment]
Working now - I successfully installed riemann-0.3.2-1.noarch.rpm , thank you!
