### ISSUE TITLE
Unable to use Env variables in riemann.config - Riemann 0.3.2

### ISSUE THREAD

**Issue by tarunngidwani** [riemann/riemann#956]
I am unable to access the value of an env variable in my riemann.config file. When I run riemann using `systemctl start riemann` the logs indicate that the value of the env variable is null.

I have **exported the env variable and tried adding to the /etc/profile and/or /etc/environments with no luck**. In the riemann.config file, I have tried accessing it directly using `System/getenv` and created a def to hold the env variables value.

I have attached some screenshots of setup. Any help would be much appreciated.

![env-var](https://user-images.githubusercontent.com/24942986/65778602-d7a02f80-e10b-11e9-98d6-bb989eeb80d7.png)

![riemann-config](https://user-images.githubusercontent.com/24942986/65778609-dc64e380-e10b-11e9-956f-f7596f3c3ae8.png)

**Comment by sanel** [comment]
These env variables are not visible from init system. If you have `/etc/sysconfig/riemann` file (centos/rhel), you can set it there. On Ubuntu it is `/etc/default/riemann`.

**Comment by tarunngidwani** [comment]
@sanel How do I access the variable once I set it in /etc/default/riemann? I tried `(System/getenv "GRAPHITE_HOST")` but that did not work and the value was still null

How does the riemann daemon know to look for variables in /etc/default/riemann on Ubuntu? I am using Systemd to start and manage the riemann daemon.

![Screenshot from 2019-09-28 11-20-24](https://user-images.githubusercontent.com/24942986/65819417-01c42100-e1e2-11e9-9300-e3d4553b2e50.png)

**Comment by faxm0dem** [comment]
Can you show the output of `systemctl cat riemann` ?

**Comment by tarunngidwani** [comment]
![systemctl-cat-riemann](https://user-images.githubusercontent.com/24942986/65897127-32d45b00-e374-11e9-89f3-eeef0cad89ca.png)

**Comment by faxm0dem** [comment]
You must add an `EnvironmentFile` directive in the `[Service]` section as explained [here](https://fedoraproject.org/wiki/Packaging:Systemd#EnvironmentFiles_and_support_for_.2Fetc.2Fsysconfig_files)

**Comment by sanel** [comment]
@tarunngidwani ah, systemd is ignoring this file too :S As @faxm0dem mentioned, you can use this riemann.service (you can find it in /etc/systemd/system somewhere):
```
[Service]
...
EnvironmentFile=-/etc/default/riemann
```
or set env variable directly in riemann.service:

```
[Service]
...
Environment="GRAPHITE_HOST=graphite-mc"
```
Make sure to reload systemd after editing this file.

**Comment by tarunngidwani** [comment]
@sanel @faxm0dem On Ubuntu 18.04 the Systemd service file is autogenerated using the SystemV init.d system. I tried adding an env variable and exporting in /etc/init.d/riemann as such:

![Screenshot from 2019-10-02 10-41-56](https://user-images.githubusercontent.com/24942986/66059283-6690bb80-e501-11e9-89a7-28ef01e7e6ca.png)

That did not work and the environment variable still comes up as null. Any ideas?

**Comment by sanel** [comment]
`/etc/default/riemann` should be read if `/etc/init.d/riemann` was used. Also, try to put `export GRAPHITE_HOST=...` in `/etc/default/riemann` as well.

If you are going to edit `/etc/init.d/riemann`, try to put `GRAPHITE_HOST` on top (before service was started).

**Comment by sanel** [comment]
Another approach is to have separate `config.clj` file (in eg `/etc/riemann/files` folder), where you set editable variables. For example:

```clojure
;; /etc/riemann/files/config.clj
(ns files.config)
;; put all global variables here
(def GRAPHITE_HOST "graphite-mc")
```
```clojure
;; /etc/riemann/riemann.config
(use 'files.config)

;; usual riemann.config stuff and GRAPHITE_HOST is visible here
(let [index (index)]
 ...
)
```

**Comment by tarunngidwani** [comment]
Thank you @sanel  @faxm0dem for all your help. Adding the env var to `/etc/default/riemann` worked. The only thing that was missing was exporting the variable

`export GRAPHITE_HOST=graphite-a` worked
