### ISSUE TITLE
Latest release 0.3.6 is not on clojars.org.

### ISSUE THREAD

**Issue by cresh** [riemann/riemann#984]
**Describe the bug**
Latest release 0.3.6 is not available at https://clojars.org/riemann .

**To Reproduce**
Add
```
[riemann "0.3.6"]
```
as a dependency in your `project.clj`.

The dependency cannot be found:
```
> lein deps
Could not find artifact riemann:riemann:jar:0.3.6 in central (https://repo1.maven.org/maven2/)
Could not find artifact riemann:riemann:jar:0.3.6 in clojars (https://repo.clojars.org/)
Could not find artifact riemann:riemann:jar:0.3.6 in local (file:maven-repository)
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

**Expected behavior**
The dependency should be retrievable from clojars.org.

**Comment by jamtur01** [comment]
Ah damn. Looks like there's an issue with my credentials and I didn't notice the failed job. I'll fix it up.

**Comment by jamtur01** [comment]
Fixed. They replaced user/password with deploy tokens and I did not realize. Thanks.
